"""Generate the checked-in formula inventory and human verification ledger.

This is a deterministic repository-maintenance tool.  It does not invoke Lean
and it never upgrades dependencies.  Kernel status is read only from the
separately reviewed verification_status_v1.json mapping.
"""

from __future__ import annotations

import argparse
import html
import json
from collections import Counter
from pathlib import Path

from inventory_theory_formulas import build_inventory


STATUS_MEANING = {
    "KERNEL_PASS": (
        "표시한 명제가 project-local axiom, `sorry`, `admit` 없이 Lean 커널을 통과"
    ),
    "CONDITIONAL_KERNEL_PASS": (
        "명시한 premise에서 결론으로 가는 합성은 통과했지만 premise의 source 증명은 미인증일 수 있음"
    ),
    "DEFINITION_ONLY": "표기·함수 정의의 전사이며 참·거짓 증명 대상이 아님",
    "PARTIAL_FORMALIZATION": "display 식의 핵심 일부만 형식화; 식 전체 PASS가 아님",
    "SOURCE_THEOREM_UNFORMALIZED": "source analytic theorem을 확인했지만 Lean 독립 증명은 없음",
    "NOT_YET_FORMALIZED": "inventory만 완료; Lean 선언 없음",
    "PARSE_REVIEW_REQUIRED": (
        "hash-pinned 원문의 수식 경계가 불완전해 안전 복구했지만 원문은 소급 변경하지 않음"
    ),
}


NOTES_BY_ID = {
    "T01-U001": "정의 전개·양수성·exp(exp(exp(1))) 위 strict monotonicity 커널 검증",
    "T01-U002": "finite record 표현",
    "T01-U003": "보조 start-bounded 정의",
    "T01-U004": "정수 경계만; G 상수성 premise는 후속",
    "T01-U005": "양의 end-bounded 정수 plateau의 오른쪽 끝점 minimum 커널 검증",
    "T07-U001": "D와 N의 함수 정의는 후속",
    "T07-U002": "순수 환대수 항등식",
    "T07-U003": "discrepancy lower premise 명시",
    "T07-U004": "상계 방향 커널 검증",
    "T07-U005": "Mathlib floor Galois connection",
    "T10-U001": "exact primality/next-prime는 매개변수",
    "T10-U002": "후보 superset soundness",
    "T10-U003": "witness soundness",
    "T10-U004": "total coverage",
    "T10-U005": "Nat exact arithmetic",
    "T11-U001": "source inequality와 대표 증가 premise",
    "55.4": "J,h 완료; cell I_j는 후속",
    "55.5": "Nat.ceil에서 세 bound 유도",
    "55.6": "grid-union measure premise 이후 scalar 합성",
    "55.10": "floor-log window p≤R<5p premise",
    "55.13": "pre-cover count 상계 이후 상수 합성",
    "55.14": "t=η/8을 명시적 premise로 사용",
    "55.15": "r0,e* gate를 premise로 사용",
    "55.16": "relative-error 대수 합성",
    "55.24": "Rankin counting은 source premise; rpow 지수 정규화는 커널 검증",
    "55.25": "Rosser--Schoenfeld prime harmonic 입력 이후 terminal 상계",
    "55.26": "S_delta·h(t) 정의와 t≠1의 정확한 적분 항등식 커널 검증",
    "55.27": "prime-sum 정규화·h(1)·decimal slack·종단 합성 검증; theta 1.01624 bound와 Stieltjes 비교는 미형식화",
    "T55-U002": "Ein interval-integral 정의 전사; delta L=w는 downstream premise",
    "55.28": "removable singularity, 두 finite interval 비교, improper integral·51/50 factor 커널 검증",
    "T55-U003": "Ein split과 103/100 상계 전체 커널 검증",
    "55.29": "Stieltjes premise 이후 Ein bound를 내부 호출해 actual parameter와 189/160 합성",
    "55.30": "2^(-3/4)<3/5와 terminal 대수 검증; prime/j-sum 비교는 premise",
    "55.31": "세 analytic/counting estimate 이후 product-log 합성",
    "55.32": "q>=200 actual log lower bounds 커널 검증",
    "55.33": "exact rational arithmetic",
    "55.34": "55.32 actual hypotheses에서 decay >4b 커널 검증",
    "55.35": "Rankin·Euler-product premise 이후 final exp cancellation 커널 검증",
    "55.36": "정수 상수만; smooth count chain은 후속",
    "55.39": "analytic/count premise 이후 최종 상계 대수",
    "56.1": "Sono c_ZFR=1/24에서 a=1/80 exact 대입",
    "56.2": "c_ZD=16에서 D_PAP=160 exact 대입",
    "56.3": "a*D_PAP=2와 C_PAP=1-exp(-2) exact 정의",
    "56.4": "0<C_PAP<1 exact 실수 부등식",
    "T56-U001": "Jutila Theorem 1의 source 진술; epsilon multiplier와 proof는 Lean 미형식화",
    "T56-U002": "finite error 합성의 명시적 analytic premise 쌍",
    "56.5": "principal/error premise 이후 finite slack 합성; analytic premise는 미인증",
    "56.6": "Jutila source epsilon/3 재매개화의 exact 지수 대수",
    "56.7": "alpha<=4/5의 low-alpha exponent bridge",
    "56.8": "DEP-R09 finite PAP 목표; Gallagher/Jutila/Maier rate와 cutoff 미형식화",
    "57.1": "Sono Proposition 5.3 source statement; analytic theorem은 Lean 미형식화",
    "57.2": "T>=2에서 log(T(1+T))<=3logT와 zero-free 폭 방향을 커널 검증",
    "57.3": "c_ZFR/3=1/72와 인쇄값 3c_ZFR=1/8의 불일치 exact 검증",
    "57.4": "McCurley Theorem 1 source statement; analytic theorem은 Lean 미형식화",
    "57.5": "McCurley Theorem 2 source statement; analytic theorem은 Lean 미형식화",
    "57.6": "direct c1=1/24의 R<12 수치 포함관계만 검증; family theorem 전체는 미형식화",
    "57.7": "Gallagher Theorem 7 source statement; hidden multiplier와 cutoff는 OPEN",
    "57.8": "c_ZD=16, D=160의 density-power boundary exact 검증",
    "57.9": "Q=x^(1/D)의 lower range에 필요한 D^2<=log x와 D=160 gate 검증",
    "57.10": "direct-McCurley repair exponent a0=1/240와 a0D=2/3 exact 검증",
    "57.11": "Gallagher-Maier nonprincipal error의 honest multiplier interface; rate 미형식화",
    "57.12": "같은 지수에서 multiplier 제거 iff K<=1을 커널 검증",
    "57.13": "log K budget으로 multiplier를 exponent에 흡수하는 충분조건 커널 검증",
    "57.14": "principal/error analytic premise 이후 multiplier 보존 one-sided 합성",
    "57.15": "교정 finite PAP analytic target; common cutoff와 source proof 미형식화",
    "58.1": "DEP-R09 fixed-coefficient pointwise PAP 목표; drop-in source 없음",
    "58.2": "exceptional modulus와 principal/nonprincipal/psi-to-pi를 포함한 finite target interface",
    "58.3": "D=160 coefficient-capacity 필요조건; 고정밀 Python 진단만 완료",
    "58.4": "최신 Sono arXiv v4와 journal에 그대로 인쇄된 상수 연결",
    "58.5": "Bennett et al. large-modulus cutoff source statement",
    "58.6": "Thorner-Zaman uniform PNT의 숨은 numerical multiplier interface",
    "58.7": "Thorner-Zaman fully explicit nonexceptional density source statement",
    "58.8": "Thorner-Zaman fully explicit exceptional-removed density source statement",
    "58.9": "Benli-Goel-Twiss-Zaman effective Deuring-Heilbronn source constants",
    "58.10": "Sono downstream coefficient capacity 함수 정의",
    "58.11": "D=160 최소 C_PAP 고정밀 진단; Lean 미형식화",
    "58.12": "D=160 총 상대오차 budget 고정밀 진단; Lean 미형식화",
    "58.13": "exp(-2) 이후 추가 finite-error slack 고정밀 진단; Lean 미형식화",
    "58.14": "낙관 C_PAP=1, D=186 coefficient 진단; Lean 미형식화",
    "58.15": "낙관 C_PAP=1, D=187 coefficient 진단; Lean 미형식화",
    "58.16": "현재 downstream 식의 낙관 integer-D capacity 결론; source 채택 전 Lean 미형식화",
    "59.1": "DEP-R09 Branch S의 fixed-D finite pointwise PAP 목표; analytic source package 없음",
    "59.2": "D=160 coefficient·total-error 고정밀 진단; Lean 미형식화",
    "59.3": "Thorner-Zaman Theorem 2.1 density source 진술; multiplier·cutoff 미형식화",
    "59.4": "숨은 multiplier를 보존하는 fixed-D transfer 진단 정의",
    "59.5": "positive K, eta, D의 logarithmic budget에서 exponential error 상계를 커널 검증",
    "59.6": "K별 최소 decay constant 80-dps 진단; Python 재계산",
    "59.7": "Jutila Theorem 1 density source 진술; epsilon multiplier·cutoff 미형식화",
    "59.8": "Thorner-Zaman Remark 2.4의 density exponent-to-theta source 관계",
    "59.9": "Jutila Theorem 1-prime source 진술; sufficiently large D cutoff 미수치",
    "59.10": "Jutila Theorem 2 source 진술; D0(epsilon)와 proof multiplier 미수치",
    "60.1": "Ramaré--Zuniga explicit coefficient의 p.54 Theorem 1-prime tau=8/5 exact 대입; 식 (3.6)에는 사용 금지",
    "60.2": "Graham--Jutila Lemma 4 full asymptotic source theorem; hidden O multiplier는 미형식화",
    "60.3": "Ramaré--Zuniga Corollary 1.3 source theorem; actual 호출의 analytic proof는 미형식화",
    "60.4": "Jutila Theorem 1-prime actual parameter 정의 전사",
    "60.5": "finite log-ratio의 exact 유리 대수를 커널 검증",
    "60.6": "finite power correction의 exponent 대수만 커널 검증; source real-power 합성은 미형식화",
    "60.7": "finite delta cutoff sufficient condition; 후속 JL5/6/8 예산과 함께 형식화 예정",
    "60.8": "Jutila Lemma 5 source asymptotic; uniform o(1) rate와 cutoff는 OPEN",
    "60.9": "Jutila Lemma 6 detector lower bound; Mellin과 tail 상수는 OPEN",
    "60.10": "Jutila Lemma 7 modified Halasz source statement; finite proof는 후속",
    "60.11": "Jutila Lemma 8 local zero-count source statement; implied constant는 OPEN",
    "60.12": "Huxley--Jutila exponent-2 source density; epsilon multiplier와 cutoff는 OPEN",
    "66.1": "Theory 60 고정 coefficient를 p.54 Theorem 1-prime scope로 재분류; exact 값은 커널 검증",
    "66.2": "Jutila p.52 식 (3.6)의 실제 theta-dependent parameter 정의",
    "66.3": "식 (3.6)의 tau_theta와 tau_theta-1 exact 유리 대수를 커널 검증",
    "66.4": "Ramaré--Zuniga coefficient의 theta-dependent exact 특수화를 커널 검증",
    "66.5": "0<theta<=1/21에서 K_BV(theta)<13/theta를 커널 검증",
    "66.6": "coefficient 끝점 slack을 포함한 유리 부등식 proof를 식 66.5와 함께 커널 검증",
    "66.7": "finite log-ratio exact 유리 대수를 커널 검증; real log/power source 연결은 별도",
    "66.8": "2 log L<=L premise 아래 18/(7 theta) transfer를 조건부 커널 검증",
    "66.9": "analytic weighted sum source는 미형식화; 두 explicit multiplier 합성만 커널 검증",
    "66.10": "Lemma 7 weight quotient 정의",
    "66.11": "elementary exp slack과 abstract quotient<5는 커널 검증; actual M,N monotonic transfer는 부분형식화",
    "66.12": "integration area lower algebra는 커널 검증; source integration identification은 부분형식화",
    "66.13": "Theory 64 detector coefficient 재사용 정의",
    "66.14": "terminal left coefficient 정의; analytic detector source proof는 Theory 64 경계 유지",
    "66.15": "off-diagonal D-exponent 전개를 커널 검증",
    "66.16": "0<theta<=1/21의 uniform negative exponent margin을 커널 검증",
    "66.17": "finite log gate premise 아래 total exponent margin을 조건부 커널 검증",
    "66.18": "Jutila p.53 terminal qualitative inequality; hidden multipliers 미형식화",
    "66.19": "A-E>0인 fail-closed terminal absorption algebra를 커널 검증",
    "66.20": "Ramaré 2016 explicit density의 additive source term; drop-in transfer는 없음",
    "T67-U001": "Jutila p.53 shifted-contour 정성 상계; source complex proof는 Lean 미형식화",
    "67.15": "source L·Gamma·contour premise 이후 exact contour coefficient 곱셈을 조건부 커널 검증",
    "T67-U002": "C_CONT(theta)의 계산기용 정의",
    "67.17": "zeta integral-test 상계를 premise로 받아 elementary contour majorant를 조건부 커널 검증",
    "T67-U003": "Jutila 식 (3.6)의 q,T,theta actual 범위 전사",
    "T67-U004": "Jutila 식 (3.6)의 s=u+iv actual 범위 전사",
    "67.1": "Jutila shifted-contour 적분 identity; complex contour 이동은 Lean 미형식화",
    "67.2": "actual contour에서 0<Re z<=1/7인 범위 대수를 커널 검증",
    "T67-U005": "primitive conductor에서 imprimitive product character로의 Euler-factor identity; Lean 미형식화",
    "67.3": "4/sqrt(6) 보정의 제곱 유리값만 커널 검증; finite prime-product inequality 전체는 부분형식화",
    "67.4": "22/7 real triangle budget은 커널 검증; complex absolute-value reduction은 미형식화",
    "67.5": "Bennett et al. Lemma 5.6 (5.3) source Rademacher bound; Lean 미형식화",
    "67.6": "nonprincipal branch의 coefficient envelope만 커널 검증; analytic source 합성 전체는 부분형식화",
    "67.7": "C_NP<9/4를 pi·sqrt 유리 상계에서 커널 검증",
    "67.8": "principal-character Dirichlet L과 zeta의 Euler-factor identity; Lean 미형식화",
    "67.9": "Hasanalizade--Shen--Wong Proposition 3.8 source zeta bound; Lean 미형식화",
    "67.10": "principal ratio의 squared cross-multiplied 16/9 상계를 커널 검증; complex quotient identity는 부분형식화",
    "T67-U006": "principal branch coefficient C_P<12는 커널 검증; source analytic 합성 전체는 부분형식화",
    "67.11": "C_P<12를 pi·sqrt 유리 상계에서 커널 검증",
    "67.12": "두 source branch 중 하나를 premise로 받아 공통 coefficient 12 합성을 조건부 커널 검증",
    "67.13": "비음수 크기의 triangle·monotonicity 합성만 커널 검증; complex-power modulus는 부분형식화",
    "T67-U007": "Gamma recurrence·Euler integral의 pointwise complex bound; Lean 미형식화",
    "67.14": "Gamma split의 finite coefficient identity만 커널 검증; complex improper integral은 부분형식화",
    "67.16": "Riemann zeta 급수 integral-test 상계; source/direct proof는 Lean 미형식화",
    "67.18": "elementary endpoint 45408은 커널 검증; zeta 포함 decimal은 비구간 수치진단이라 부분형식화",
    "68.1": "actual primed outer absolute-sum 함수 정의",
    "68.2": "Jutila Lemma 3와 one-variable envelope를 premise로 받은 3R^2 종단 대수는 조건부 커널 검증",
    "68.3": "Jutila Lemma 2의 h Euler-product 정의 전사",
    "T68-U001": "actual f(p)=mu(p)phi(p)=-(p-1) 특수화 전사",
    "T68-U002": "squarefree lcm support와 floor endpoint는 문서·exact Python 검산; 전체 prime-factor induction 미형식화",
    "68.4": "exclusive/common local 절댓값 대수는 커널 검증; 전체 Euler-product 곱셈은 부분형식화",
    "68.5": "공통소수 local printed bound는 커널 검증; Jutila Lemma 3 전체는 source theorem 미형식화",
    "68.6": "exclusive/common reciprocal local factor는 커널 검증; delta identity 전체 prime-factor induction은 부분형식화",
    "68.7": "one-variable outer weight와 합의 정의",
    "68.8": "Jutila printed product bound를 premise로 한 Cartesian-square 합성; finite family 전체는 Lean 미형식화",
    "T68-U003": "squarefree divisor identity는 문서·exact Python 검산; prime-factor induction 미형식화",
    "68.9": "finite divisor double-count와 floor(K/d)/d 상계는 커널 검증; actual subset-extension은 부분형식화",
    "68.10": "Mathlib zeta(2) identity와 pi<3.15에서 finite reciprocal-square sum<5/3을 커널 검증",
    "T68-U004": "one-variable 5K/3 premise에서 pair 3K^2 및 floor endpoint 합성을 조건부 커널 검증",
    "T68-U005": "Theory 67 shifted-contour source/conditional 결과의 재사용",
    "68.11": "contour와 Lemma 3 multiplier 합성 정의",
    "68.12": "Theory 67 elementary contour 상계 이후 factor 3 coefficient 항등식을 조건부 커널 검증",
    "68.13": "theta=1/21의 exact endpoint 136224를 커널 검증",
    "69.1": "JL7-RES actual theta,D,L 범위 전사",
    "69.2": "analytic residue bound를 premise로 받은 endpoint coefficient 52 합성을 조건부 커널 검증",
    "69.3": "Jutila 식 (3.6)의 R,z1,x actual parameter 전사",
    "69.4": "선택 shifted zero의 actual real·height 범위 전사",
    "69.5": "Jutila printed p.53 principal residue source 식; complex·character 합은 Lean 미형식화",
    "69.6": "Lemma 3 reciprocal local factor는 Theory 68에서 부분형식화; full diagonal product identity는 source theorem",
    "69.7": "대각화 뒤 actual finite r-sum 정의",
    "69.8": "xi·eta interval endpoint와 길이 정의",
    "69.9": "Gamma recurrence에 의한 removable-pole identity; complex integral 전체는 Lean 미형식화",
    "69.10": "pole-cancelled ladder kernel 정의",
    "69.11": "closed-form은 Python 독립 quadrature로 검산; Lean 형식화 대기",
    "69.12": "xi·eta rational coefficient는 커널 검증; d-a와 실제 log 연결은 부분형식화",
    "69.13": "interval coefficient product<7은 커널 검증; triple-integral identification은 부분형식화",
    "69.14": "off-diagonal coefficient<7은 커널 검증; complex modulus transfer는 부분형식화",
    "T69-U001": "0<=Re z<=2/21에서 19/21<=Re(1-z)<=1을 커널 검증",
    "69.15": "40/19<3 rational endpoint는 커널 검증; complex Gamma Euler-integral 비교는 부분형식화",
    "69.16": "Jutila selected-system spacing Delta=1/L 정의",
    "69.17": "two-sided Basel coefficient 10/3은 커널 검증; character-height ordering은 source theorem 미형식화",
    "T69-U002": "diagonal pair coefficient 21의 exact 항등식 커널 검증",
    "T69-U003": "off-diagonal pair coefficient 70의 exact 항등식 커널 검증",
    "69.18": "theta<=1에서 row coefficient 91 합성을 커널 검증; analytic pair premise는 조건부",
    "69.19": "Rankin·Euler-product actual r-sum direct proof; Lean 전체 형식화 대기",
    "69.20": "excluded-prime local ratio의 exponential 상계; Python 검산, Lean 형식화 대기",
    "69.21": "Rankin·excluded-prime·zeta rational multipliers 2*3*2=12만 부분형식화",
    "T69-U004": "Jutila p.53 바깥 residue prefactor 전사",
    "69.22": "12*91*theta<=52 endpoint와 nonnegative-base 합성을 커널 검증",
    "70.1": "JL7-ABSORB actual nonprincipal near-one fixed-modulus 범위 전사",
    "70.2": "half-margin premise 아래 selected-system bound와 exact C_J 계수 합성을 조건부 커널 검증",
    "70.3": "한 parity system bound에서 even/odd local zero-count로의 비음수 합성을 조건부 커널 검증",
    "70.4": "weighted call 34/theta^2와 denominator quotient 5의 exact 단일 곱을 커널 검증",
    "70.5": "Theory 68 contour-plus-Lemma3 multiplier 재사용 정의",
    "70.6": "detector·integration-area 정의와 lower 일부는 선행 Lean 선언; analytic identification은 미형식화",
    "70.7": "pi^2<10과 rational detector strict lower를 커널 검증",
    "70.8": "Jutila Lemma 7 detector left side의 source analytic 식; Lean 미형식화",
    "70.9": "predecessor source estimates를 합친 actual terminal analytic inequality; 전체 Lean 미형식화",
    "70.10": "A,B,E 정규화와 generic terminal algebra 일부를 조건부 형식화",
    "70.11": "normalized off-diagonal coefficient E 정의",
    "70.12": "q/phi(q)<=6L premise에서 exact square factor 36을 조건부 커널 검증",
    "70.13": "half-margin ratio P와 logarithmic cutoff 정의",
    "70.14": "exponential cutoff와 E<=A/2 premise에서 strict terminal 합성을 조건부 커널 검증",
    "70.15": "log P<=P를 사용한 rational fallback implication을 커널 검증",
    "70.16": "L>=exp(8)에서 4logL/L<=29/252 finite gate를 커널 검증",
    "70.17": "JL6·finite-log·absorption cutoff의 공통 maximum 정의",
    "70.18": "half-margin terminal algebra와 exact selected-system coefficient를 조건부 커널 검증",
    "70.19": "theta=1/21의 Cpre,Cbar,cbar,gamma,P,C_J exact endpoint를 커널 검증",
    "71.1": "가변 modulus 평균의 공통 D=Q^2*T와 L=log D 정의",
    "71.2": "averaged terminal과 even/odd local-count premise 이후 near-one primitive nonprincipal count를 조건부 커널 검증",
    "71.3": "x와 local square radius r의 actual averaged 정의",
    "71.4": "Jutila 식 (3.7) generalized Halasz source inequality; complex/character proof는 Lean 미형식화",
    "71.5": "modulus-dependent pseudocharacter detector 정의 전사",
    "71.6": "각 primitive conductor의 Mellin scale과 common R,z2 정의",
    "71.7": "상·하 envelope 방향의 비음수 곱 대수와 exponent identity만 커널 검증; real-rpow/source identification은 부분형식화",
    "71.8": "0<=theta<=1/21의 common power-condition exponent margin을 선행 커널 정리로 검증",
    "71.9": "Mellin exponent 대수와 theta=1/21 endpoint는 커널 검증; complex Mellin bound와 real-rpow transfer는 부분형식화",
    "71.10": "four-loss common averaged detector cutoff의 기호적 maximum 정의",
    "71.11": "source detector identity를 제외한 four-part loss budget과 (1-theta) 회복만 부분형식화",
    "71.12": "phase magnitude·alignment 중 scalar totient cancellation만 커널 검증",
    "71.13": "phase-weighted complex sum과 finite-family 합은 미형식화; 항별 scalar cancellation만 커널 검증",
    "71.14": "primitive product가 principal인 정확한 character 조건은 source theorem으로 보존",
    "71.15": "phase-residue-pseudocharacter totient factor의 exact scalar cancellation을 커널 검증",
    "71.16": "same-character residue analytic premise 이후 multiplier 52와 phase cancellation을 조건부 커널 검증",
    "71.17": "product conductor lcm<=q_j*q_k<=Q^2의 표준 유한 정수식; Lean 형식화 대기",
    "71.18": "두 q/phi(q)<=6L premise에서 normalized phase-pair factor<=36을 조건부 커널 검증",
    "71.19": "Theory 70 terminal coefficient의 averaged 재사용 정의",
    "71.20": "averaged generalized-Halasz analytic 합성은 미형식화; common L^2 cancellation만 부분형식화",
    "71.21": "positive common L^2를 나눈 normalized A,B,E 식을 analytic raw premise 아래 조건부 커널 검증",
    "71.22": "averaged detector·log gate·half-margin cutoff의 공통 maximum 정의",
    "71.23": "half-margin premise 아래 Theory 70 selected-system coefficient를 raw Q 손실 없이 조건부 커널 검증",
    "71.24": "q<=Q, Q,T>=1, D=Q^2*T에서 두 logarithmic upper bound를 커널 검증",
    "72.1": "Gallagher zero-density integral의 far/near alpha 구간 정의",
    "72.2": "Gallagher 식 (30)의 explicit-formula 평균 구조; 숨은 multiplier와 cutoff는 OPEN",
    "72.3": "Gallagher 식 (30)의 Stieltjes zero-density identity; analytic identity 전체는 미형식화",
    "72.4": "Bennett et al. Theorem 1.1 source statement; peer-reviewed analytic theorem은 Lean 미형식화",
    "72.5": "T=Q^5의 elementary logarithm envelope; Lean 순차 형식화 대기",
    "72.6": "Bennett source theorem에서 per-character coarse upper로 가는 analytic 합성",
    "72.7": "per-character와 character-count premise에서 family total-zero upper를 조건부 커널 검증",
    "72.8": "far integral 평가를 premise로 받은 endpoint X^-1 cancellation만 커널 검증",
    "72.9": "PAP X,Q,T와 common family scale D의 정의",
    "72.10": "total-zero와 real-power 정규화를 premise로 받은 far upper 합성을 조건부 커널 검증",
    "72.11": "theta=1/21,d=160의 far exponent와 coefficient를 exact 유리수로 커널 검증",
    "72.12": "y<=exp(y/2)를 통한 far budget cutoff; Lean 순차 형식화 대기",
    "72.13": "near integral의 L,C_J,kappa,lambda,A,B,eta,delta0 정의",
    "72.14": "두 exponential antiderivative를 premise로 받고 switch 항의 exact cancellation을 부분형식화",
    "72.15": "theta=1/21,d=160의 kappa=22와 lambda=69/80을 커널 검증",
    "72.16": "near certificate의 asymptotic limit; calculus와 고정밀 진단은 Lean 미형식화",
    "73.1": "selected-system coefficient 정의; 여섯 factor의 generic identity는 식 73.2와 함께 커널 검증",
    "73.2": "nonzero theta premises 아래 여섯 loss factor와 baseline coefficient의 exact 항등식을 커널 검증",
    "73.3": "theta=1/21의 detector와 baseline coefficient exact 정수 산술을 커널 검증",
    "73.4": "tightened exact rational composition은 커널 검증; decimal과 analytic factor premises는 별도",
    "73.5": "baseline/tightened exact 개선비는 커널 검증; decimal은 비구간 진단",
    "73.6": "exp(-2) PAP budget에서 얻은 120-dps coefficient cap; directed interval certificate 아님",
    "73.7": "tightened coefficient의 PAP budget 초과비 120-dps 진단; exact source ledger로 재계산",
    "T73-U001": "Lemma 7 denominator weight 정의 전사",
    "73.8": "M,N 단조 transfer는 문서 proof; reduced exponential quotient는 식 73.10과 함께 커널 검증",
    "73.9": "문서의 derivative proof 대신 더 짧은 exp order proof로 식 73.10 결론을 커널 검증",
    "73.10": "rho>=4, t>=1/rho에서 full quotient<8/5를 커널 검증; displayed limit identity 자체는 부분형식화",
    "73.11": "Ramaré--Zuniga coefficient의 endpoint exact rational은 커널 검증; source analytic theorem은 미형식화",
    "73.12": "Theory 66 source parameter에서 나온 finite log-ratio identity; 이번 Lean batch에서는 미형식화",
    "73.13": "L>=441에서 log(L)/L antitonicity와 exp(8)>441을 이용한 strict rational upper를 커널 검증",
    "73.14": "source weighted inequality는 미형식화; endpoint rational multiplication은 커널 검증",
    "73.15": "denominator 8/5와 weighted endpoint rational의 exact preterminal 합성을 커널 검증",
    "73.16": "height-row coefficient 정의 전사",
    "73.17": "0<=theta<=1/21의 row monotonic upper와 endpoint exact rational을 커널 검증",
    "73.18": "q<=Q, L=log(Q^2T)>0의 averaged log-ratio<=1/2를 커널 검증",
    "73.19": "Theory 69 Rankin Euler-product 계산의 sharpened analytic 합성; Lean 독립 proof는 없음",
    "73.20": "Mathlib six-term exp remainder로 e^(23/42)*(442/441)<7/4를 커널 검증",
    "T73-U002": "six-term exponential upper의 rational 계산은 73.20 proof 내부에서 커널 검증",
    "T73-U003": "7/4와 rational upper의 exact positive slack은 73.20 proof 내부에서 커널 검증",
    "73.21": "7/4와 exact height row의 residue rational 합성을 커널 검증; Rankin premise는 식 73.19 경계",
    "73.22": "endpoint area rational equality는 커널 검증; A_int analytic lower identification은 선행 premise",
    "73.23": "E<=A/m과 normalized terminal premise에서 arbitrary strict absorption을 조건부 커널 검증",
    "73.24": "exponential remainder에서 E<=A/m으로 가는 symbolic cutoff; Lean 순차 형식화 대기",
    "73.25": "m=10^6 cutoff의 120-dps diagnostic; directed interval certificate 아님",
    "T73-U004": "normalized terminal inequality의 재사용 정의",
    "73.26": "d=186,c1=1/24,theta=1/21의 lambda와 두 exponent를 exact rational로 커널 검증",
    "73.27": "unit-C_J near kernel의 transcendental 120-dps 진단; directed interval certificate 아님",
    "73.28": "baseline/tightened near upper의 120-dps 진단; directed interval certificate 아님",
    "73.29": "theta=1/21의 theta^-6 exact integer를 커널 검증; proof-architecture 불가능성 정리는 아님",
    "74.1": "선별 후보 집합의 source-screen 결론; 문헌 전수 불가능성 명제가 아니며 Lean 형식화 대상 아님",
    "74.2": "현재 downstream pointwise PAP target 계약의 정의 전사",
    "74.3": "D=160 minimum C_PAP 100-dps 선행 진단; directed interval certificate 아님",
    "74.4": "Ramaré 2016 Theorem 1.1 source analytic statement; Lean 독립 proof 없음",
    "74.5": "Ramaré direct-insertion 변수 정규화 정의",
    "74.6": "main-term 일반 변환은 문서·Python 검산; d=186 rational exponent만 커널 검증",
    "74.7": "additive-term 일반 변환은 문서·Python 검산; d=186 rational exponent만 커널 검증",
    "74.8": "zero-free edge의 d=186,c1=1/24 exact mass만 커널 검증",
    "74.9": "Ramaré source RHS의 unit-slice main certificate 하한; 문서 직접 proof와 Python 범위검사",
    "74.10": "Ramaré additive certificate 하한; 문서 직접 proof와 Python 범위검사",
    "74.11": "d=186 Ramaré exponent margins와 zero-free edge mass exact rational 커널 검증",
    "74.12": "Ramaré printed source-range max의 100-dps 진단; directed interval certificate 아님",
    "74.13": "direct slice certificate의 100-dps 진단; 실제 prime error 하한이 아님",
    "74.14": "Thorner--Zaman explicit Bombieri source statements; analytic theorem은 Lean 미형식화",
    "74.15": "99,170,198의 d=186 integer capacity 비교를 커널 검증",
    "74.16": "Chen--Gupta--Li arXiv v2 asymptotic source statement; o(1)과 analytic proof 미형식화",
    "74.17": "Friedlander--Iwaniec Lemma 7.1 source sieve statement; analytic premise는 미형식화",
    "74.18": "80*18*52600과 coefficient comparison의 exact arithmetic을 커널 검증",
    "75.1": "세 transfer 후보의 좁은 feasibility 판정; analytic 불가능성 정리가 아니며 Lean 형식화 대상 아님",
    "75.2": "Maier--Gallagher actual PAP 변수와 family scale 정의 전사",
    "75.3": "first y-slice 정의 중 d=186,c1=1/24의 두 endpoint 산술을 부분 커널 검증",
    "75.4": "두 analytic upper premise가 주어졌을 때 pointwise min의 ordered-field 단조성을 조건부 커널 검증",
    "75.5": "Ramaré/Jutila first-slice lower는 문서·Python 검산; edge rational만 부분 형식화",
    "75.6": "Theory 73의 tightened exact coefficient kernel proof를 재사용",
    "75.7": "source 최소점에서의 두 transcendental lower 함수; Python 120-dps와 문서 미분 proof",
    "75.8": "finite d endpoint reduction의 elementary calculus; Lean 순차 형식화 대기",
    "75.9": "8602 decimal은 고정밀 diagnostic; endpoint와 coarse 1/8602<1/7만 커널 검증",
    "75.10": "exp(-2) 대비 required attenuation 120-dps diagnostic; directed interval certificate 아님",
    "75.11": "normalized nonnegative zero-frequency Mellin factor 정의",
    "75.12": "support와 positivity에서 오는 elementary integral bound; 문서 직접 proof, Lean 미형식화",
    "75.13": "zero-frequency support lower와 attenuation 비의 고정밀 diagnostic",
    "75.14": "support expansion 필요조건의 고정밀 diagnostic; original interval 보존 불가를 뜻함",
    "75.15": "signed weight Mellin continuity의 elementary integral inequality; 문서 직접 proof, Lean 미형식화",
    "75.16": "target attenuation에서 signed condition-number necessary lower; Lean 순차 형식화 대기",
    "75.17": "Gallagher 식 (30)의 positive zero-count integral 구조; source analytic identity 미형식화",
    "75.18": "pre-absolute-value residue-class zero contribution 정의",
    "75.19": "complex Cauchy와 second-moment를 explicit premise로 받은 terminal scale만 조건부 커널 검증",
    "76.1": "explicit 후보 실패와 aggregate moment open 경로의 source-screen 판정; 전역 불가능성 명제가 아님",
    "76.2": "residue-class von Mangoldt error 정의",
    "76.3": "현재 coefficient capacity와 near budget 정의",
    "76.4": "기존 pointwise PAP 목표 정의",
    "76.5": "Maier aggregate admissible-column error 목표 정의",
    "76.6": "Maier printed Lemma 2 적용과 최종 aggregate prime count; source analytic proof 미형식화",
    "76.7": "Akbary--Hambrook Theorem 1.2 source statement; Lean 미형식화",
    "76.8": "published RHS의 positive floor와 120-dps diagnostic; actual error 하한이 아님",
    "76.9": "Sedunova Theorem 1.2 source statement; Lean 미형식화",
    "76.10": "Sedunova source의 F(x,Q,Q1) 정의",
    "76.11": "Q1=1 direct certificate floor의 120-dps diagnostic; actual error 하한이 아님",
    "76.12": "Bennett et al. Theorem 1.1 pointwise source statement; Lean 미형식화",
    "76.13": "Bennett large-q source constants와 cutoff; Lean 미형식화",
    "76.14": "Y=q^d cutoff normalization은 문서 대수와 Python 검산; transcendental source range 미형식화",
    "76.15": "normalized cutoff와 sqrt/log lower premises에서 d<=186 모순을 조건부 커널 검증",
    "76.16": "first large-q boundary와 primorial checkpoint의 120-dps cutoff diagnostic",
    "76.17": "Bennett error를 PAP relative scale로 옮긴 elementary normalization; Python 검산",
    "76.18": "q=510510,d=186 checkpoint의 120-dps diagnostic; directed interval certificate 아님",
    "76.19": "character explicit-formula residue error 표현 정의",
    "76.20": "admissible residue aggregate character identity; character theory 전체 미형식화",
    "76.21": "finite character orthogonality source theorem; Lean 미형식화",
    "76.22": "aggregate Cauchy premise를 받은 scalar terminal implication을 조건부 커널 검증",
    "76.23": "M-times second-moment budget에서 aggregate error 목표로의 종단 합성을 조건부 커널 검증",
    "76.24": "필요한 hypothetical individual-primorial natural-order variance theorem; 현재 source 없음",
    "76.25": "hypothetical variance에서 필요한 scale condition으로의 대수; analytic premise 미확보",
    "77.1": "restricted-residue variance source-screen 결론; 전역 불가능성 명제가 아님",
    "77.2": "Maier printed matrix 정의 전사",
    "77.3": "Maier admissible residue 집합 정의 전사",
    "77.4": "Maier p.267 formula (I) source lower bound; Lean 독립 proof 없음",
    "77.5": "Maier p.267 formula (II) source pair upper bound; R10에서 별도 명시화 필요",
    "77.6": "admissible-set character coefficient 정의",
    "77.7": "finite character orthogonality source theorem; Lean 미형식화",
    "77.8": "principal-character coefficient M의 finite character fact; Lean 미형식화",
    "77.9": "total과 principal energy에서 nonprincipal energy를 빼는 실수대수만 커널 검증",
    "77.10": "Theory 76 character explicit-formula normalization 재사용 정의",
    "77.11": "principal relative-error 입력 계약 정의",
    "77.12": "nonprincipal Cauchy premise 이후 scalar terminal 합성을 조건부 커널 검증",
    "77.13": "principal-separated moment budget에서 weighted target으로의 합성을 조건부 커널 검증",
    "77.14": "두 충분 budget의 exact ratio; Python exact/high-precision 검산",
    "77.15": "Cauchy equality를 만드는 abstract aligned error-vector 정의",
    "77.16": "alignment equality의 scalar 항등식만 커널 검증; actual prime-error alignment 주장이 아님",
    "77.17": "Fiorilli--Martin source implication은 미형식화; d=21,186 endpoint 대입만 커널 검증",
    "77.18": "현재 필요한 direct weighted-correlation analytic target 정의",
    "77.19": "Dirichlet character의 nonunit zero convention에서 오는 shifted-sum identity; Lean 미형식화",
    "77.20": "Maier U 정의와 q^(o(1)) scale; analytic asymptotic 미형식화",
    "78.1": "Maier Lemma 6의 fixed congruence pair 원문 전사",
    "78.2": "fixed pairwise-coprime partition에서 CRT residue가 하나라는 source/direct 수론 사실; Lean 미형식화",
    "78.3": "Sono/FMT sieve residue vector 정의",
    "78.4": "Maier prime-product 삼분할 정의",
    "78.5": "Sono/FMT survivor set 정의 전사",
    "78.6": "각 sieve vector가 정하는 CRT m congruence 정의 전사",
    "78.7": "동일 construction family 위 세 bad set 정의",
    "78.8": "세 bad-set cardinality 합이 family보다 작다는 finite selection premise",
    "78.9": "finite union bound로 simultaneous good candidate 존재를 커널 검증",
    "78.10": "finite Markov count 식은 exact Python 검산; analytic badness 합은 입력",
    "78.11": "singleton family의 strict bad-count budget이 세 count 0을 강제함을 커널 검증",
    "78.12": "Sono/FMT vector별 direct weighted-correlation 목표 정의",
    "78.13": "vector-dependent character coefficient 정의; analytic 상계는 OPEN",
    "79.1": "FMT first-stage A와 conditional second-stage N-prime의 joint-law factorization 정의",
    "79.2": "Theory 55 uniform conditional failure에서 얻는 project sieve-good mass; full probability proof는 Lean 미형식화",
    "79.3": "최종 residue가 outer A와 inner N-prime 양쪽에 의존한다는 source 구조 정의",
    "79.4": "Theory 55 식 (55.17)의 outer failure bound 재사용",
    "79.5": "Theory 55 식 (55.20)--(55.21)의 uniform conditional inner failure 재사용",
    "79.6": "조건부 law를 합한 project finite-mass proof; exact Python 검산, Lean probability 미형식화",
    "79.7": "failure upper의 analytic premise는 입력; 마지막 exact 실수대수 identity를 커널 검증",
    "79.8": "joint construction outcome에 의존하는 weighted character coefficient 정의",
    "79.9": "같은 joint law의 union lower bound; analytic correlation input은 OPEN",
    "79.10": "same-law correlation failure가 sieve mass보다 작을 때 positive slack인 scalar terminal",
    "79.11": "비음수 failure에서 crude union gate가 product gate를 함의하는 조건부 실수대수",
    "79.12": "fiberwise probability 식은 미형식화; 대응 finite outer/fiber selection은 커널 검증",
    "79.13": "Markov probability 식은 exact Fraction 검산; actual badness expectation은 OPEN",
    "80.1": "actual final FMT joint outcome 정의",
    "80.2": "Sono primorial modulus와 fixed offset interval 정의",
    "80.3": "joint outcome별 survivor set과 count 정의",
    "80.4": "nonunit-zero character convention의 shifted full-interval identity; Lean 미형식화",
    "80.5": "nonprincipal weighted prime-error observable 정의",
    "80.6": "남은 positive relative-error budget 정의",
    "80.7": "direct weighted-correlation target 정의",
    "80.8": "outer-good domain의 divide-by-zero-safe normalized squared badness 정의",
    "80.9": "normalized target equivalence는 Python 경계검사; character absolute-value Lean proof 대기",
    "80.10": "finite tower와 flat joint-atom 합의 대수 identity를 커널 검증",
    "80.11": "Theory 79의 parameterized sieve-good mass 재사용",
    "80.12": "Markov probability input은 analytic premise; exact finite fixture 검산",
    "80.13": "global joint-success probability lower는 미형식화; positive terminal만 조건부 커널 검증",
    "80.14": "global moment strict gate에서 positive terminal mass로 가는 조건부 커널 검증",
    "80.15": "outer-good conditional moment 정의",
    "80.16": "conditional probability lower는 미형식화; product positivity terminal만 커널 검증",
    "80.17": "conditional moment strict gate의 scalar terminal을 커널 검증",
    "80.18": "uniform outer-good-fiber analytic moment target; source theorem 미발견",
    "80.19": "uniform-fiber strict gate의 같은 scalar terminal을 조건부 커널 검증",
    "80.20": "raw same-law second-moment analytic input; source theorem 미형식화",
    "80.21": "positive pointwise denominator의 정규화 identity·단조성을 조건부 커널 검증",
    "81.1": "FGKMT Theorem 3의 sequential partially-sifted filtration 정의; source 구조 전사",
    "81.2": "outer-good과 conditional inner-good의 교집합인 final sieve-good 사건 정의",
    "81.3": "Theory 79의 parameterized final sieve-good mass 재사용; probability measure proof는 미형식화",
    "81.4": "Theory 55 floor의 actual 사건영역을 교정하고 positive terminal algebra를 커널 검증",
    "81.5": "final sieve-good 사건에서만 나누는 normalized squared badness 정의",
    "81.6": "corrected same-law normalized moment 정의",
    "81.7": "Markov probability lower는 premise; strict gate 이후 positive terminal을 커널 검증",
    "81.8": "corrected final sieve-good strict moment gate의 terminal을 조건부 커널 검증",
    "81.9": "final sieve-good 사건에 제한된 raw analytic second-moment input; source theorem OPEN",
    "81.10": "같은 사건의 positive survivor floor를 쓰는 raw-to-normalized 단조성을 커널 검증",
    "81.11": "final residue와 CRT shift의 congruence convention 정의",
    "81.12": "CRT congruence와 한 prime 생존조건의 elementary equivalence; Lean 순차 형식화 대기",
    "81.13": "Theory 55 sifted set과 Theory 80 gcd-survivor set의 exact identification; Lean 순차 형식화 대기",
    "81.14": "한 prime coordinate만 바뀌는 squarefree CRT shift premise 정의",
    "81.15": "두 residue class containment의 초등 finite proof와 Python 전수검산; full Finset proof 대기",
    "81.16": "symmetric-difference bound에서 absolute count bound로 가는 terminal을 커널 검증",
    "81.17": "shifted Dirichlet-character coefficient 정의",
    "81.18": "P=65 finite character 값은 exact Python 검산; 합의 integer arithmetic만 Lean 형식화",
    "81.19": "character 변화 3이 membership bound 2보다 큼의 integer terminal을 커널 검증",
    "81.20": "추가 구조 없는 두 length-N character 합의 trivial bound; Lean 순차 형식화 대기",
    "81.21": "weighted L1 triangle bound; actual PAP-sized analytic weight는 OPEN",
    "81.22": "actual FMT filtration의 Doob increment 정의",
    "81.23": "Freedman형 bounded increment·conditional variance 요구식; actual input OPEN",
    "81.24": "CRT shift 전후 reduced-residue count-difference 함수 정의",
    "81.25": "finite character orthogonality/Parseval source identity; Lean 미형식화",
    "81.26": "weighted increment의 Cauchy--Schwarz 경로; actual complex vector 형식화 대기",
    "83.1": "prescribed primorial power-regime normalization 정의",
    "83.2": "Theory 82 strict character-energy gate 재사용; analytic V input은 OPEN",
    "83.3": "Montgomery--Vaughan 직접 certificate RHS 정의",
    "83.4": "source upper/lower premise 이후 gate가 certificate RHS 아래라는 종단 합성만 조건부 커널 검증",
    "83.5": "upper RHS가 gate 위이면 strict 결론이 논리적으로 나오지 않는 countermodel을 부분형식화",
    "83.6": "power exponent delta=1/d 정의와 endpoint 전사",
    "83.8": "Fiorilli--Martin Proposition 2.2 source implication; analytic proof 미형식화",
    "83.9": "Theory 77에서 이미 검사한 rational endpoint 재사용; display 전체는 부분형식화",
    "83.10": "Montgomery--Vaughan Theorem 1 source statement; 원문·페이지·hash 고정",
    "83.11": "Farey spacing을 사용한 additive specialization; finite complex proof 미형식화",
    "83.12": "primitive Gauss sum·Bessel multiplicative large-sieve source 합성; Lean 미형식화",
    "83.13": "Lambda-square sum과 L 표기 정의",
    "83.14": "Dusart Theorem 5.2 source theorem; Lean 독립증명 없음",
    "83.15": "Dusart endpoint substitution의 실수 analytic 합성; Python 고정밀 검산",
    "83.15a": "L=8 Dusart coefficient의 rational lower certificate를 커널 검증; 실수로그 monotonicity는 문서 proof",
    "83.16": "current L range에서 quarter lower; source log inequalities Lean 미형식화",
    "83.17": "prime half-interval로 Lambda-square lower를 얻는 문서 proof; Lean 미형식화",
    "83.18": "large-sieve published RHS의 source-derived lower envelope",
    "83.19": "L>=21t와 log2<t 이후 5t strict margin을 조건부 커널 검증",
    "83.20": "q개 atom의 finite pigeonhole lower; Lean 순차 형식화 대기",
    "83.21": "best-case probability·survivor factor 범위 전사",
    "83.22": "각 nonnegative factor 상계에서 best-entropy gate envelope로 가는 곱셈 단조성을 조건부 커널 검증",
    "83.23": "Rosser--Schoenfeld 일반식 source theorem; Lean 독립증명 없음",
    "83.24": "exception coefficient를 전 q에 확대한 안전 envelope; source theorem 미형식화",
    "83.25": "strict 비교용 scalar 함수 정의",
    "83.26": "미분식·양수성 문서 proof와 Python 진단; transcendental source 전부는 Lean 미형식화",
    "83.27": "elementary exp/log endpoint interval 문서 proof; Lean 순차 형식화 대기",
    "83.28": "120-dps endpoint 교차검산; directed interval certificate는 아님",
    "83.29": "V=gate exact countermodel로 raw upper certificate의 strict-gate 논리 불충분성을 커널 검증",
    "84.1": "prescribed primorial power regime normalization 재사용",
    "84.2": "Theory 82 strict character-energy gate 재사용; analytic V input은 OPEN",
    "84.3": "Theory 83 length-mass lower와 best gate upper의 합성; analytic source premise 뒤 terminal만 조건부 형식화",
    "84.4": "primitive-character conductor count의 Moebius inversion source identity; exact Python 검산",
    "84.5": "character induction의 unique-conductor partition identity; exact Python 검산, Lean source theorem 미형식화",
    "84.6": "principal conductor 1을 제외한 nonprincipal count; exact Python 검산",
    "84.7": "squarefree primitive-character count product formula; exact Python 검산",
    "84.8": "even squarefree modulus의 positive conductor-level count; exact Python 검산",
    "84.9": "Baier Theorem 2 식 (6)의 sparse-modulus large-sieve source statement; Lean 미형식화",
    "84.10": "current power regime와 Baier source improvement range의 비교",
    "84.11": "한 sampled frequency의 universal length-term extremizer; exact finite Python 검산",
    "84.12": "가장 유리한 generic sparse certificate RHS 정의",
    "84.13": "nonnegative sparse tail이 length term을 줄이지 못함을 커널 검증",
    "84.14": "Theory 83 analytic lower를 premise로 한 sparse-certificate strict barrier terminal을 조건부 커널 검증",
    "84.15": "Montgomery--Vaughan 2001 Theorem 5 signed Moebius sum source statement; implicit constant, Lean 미형식화",
    "84.16": "signed cancellation과 L1의 차이를 보이는 finite witness; Python exact 검산",
    "84.17": "Friedlander--Goldston fixed-q variance 정의",
    "84.18": "Friedlander--Goldston 식 (1.5)의 GRH conditional implicit upper; source theorem 미형식화",
    "84.19": "Friedlander--Goldston source range와 current d-range 비교; analytic theorem은 미형식화",
    "84.20": "nonnegative sparse tail의 length-term 단조성을 독립 커널 검증",
    "84.21": "source length lower premise 뒤 generic sparse certificate가 gate 위임을 조건부 커널 검증",
    "85.1": "centering·Parseval identity premise에서 principal correction을 버린 character-energy upper를 조건부 커널 검증",
    "85.2": "Vaughan printed 식 (1.1)--(1.2)의 psi와 residue variance 정의",
    "85.3": "reduced-residue total과 principal-character sum의 정의",
    "85.4": "finite center-shift identity; exact rational Python 검산, finite-sum Lean proof는 미형식화",
    "85.5": "finite character Parseval source identity; Lean 독립증명 없음",
    "85.6": "exact bridge identity를 premise로 받은 nonnegative principal-error terminal을 조건부 커널 검증",
    "85.7": "Vaughan variance strict upper에서 Theory-82 energy gate로의 terminal을 조건부 커널 검증",
    "85.8": "Vaughan natural main term U 정의 전사",
    "85.9": "dyadic modulus moment M_k 정의 전사",
    "85.10": "Vaughan Theorem 1의 fixed-A source range; analytic theorem은 Lean 미형식화",
    "85.11": "Vaughan Theorem 1 moment bound source statement; implicit constants 미수치",
    "85.12": "Theorem 1의 F bound source statement; positive c와 multiplier 미수치",
    "85.13": "nonnegative moment에서 한 dyadic 항을 추출하는 finite 단계; 전체 real-root formalization은 대기",
    "85.14": "current Y=q^d 대입의 fixed-A 필요조건; Python log-space boundary 검산",
    "85.15": "fixed A,d에서 range ratio가 0으로 가는 analytic limit; Lean 미형식화",
    "85.16": "Vaughan Theorem 2의 GRH source range; Lean 미형식화",
    "85.17": "Vaughan Theorem 2 moment·F bound source statement; conditional·implicit",
    "85.18": "delta<=1/21과 epsilon>=0에서 delta<3/4+epsilon을 커널 검증",
    "85.19": "Vaughan Theorem 3 partial singular-series source statement; implicit error constants",
    "86.1": "FMT outer residue space와 정확한 cardinality 정의",
    "86.2": "support-restricted outer-fiber maximum energy 정의",
    "86.3": "actual conditional event subprobability의 finite 평균 상계; Python exact 검산, Lean finite-sum proof는 대기",
    "86.4": "fiber-energy upper를 premise로 Theory-81 strict normalized gate까지 조건부 커널 검증",
    "86.5": "FMT printed p.12의 outer uniform law; source probability theorem은 Lean 미형식화",
    "86.6": "actual two-stage conditional-law factorization; source probability law는 Lean 미형식화",
    "86.7": "actual conditional final-shift support 정의",
    "86.8": "FMT final extension의 outer coordinate 보존; source congruence는 Lean 미형식화",
    "86.9": "outer coordinate 보존에서 오는 fiber disjointness; Python CRT fixture 검산, Lean 대기",
    "86.10": "sieve-good event와 shift의 conditional subprobability 정의",
    "86.11": "conditional event mass의 nonnegative subprobability 성질; Lean finite probability proof 대기",
    "86.12": "actual same-law raw moment의 outer tower 합; Lean finite probability proof 대기",
    "86.13": "fiber subprobability average를 maximum으로 묶는 finite inequality; Python exact 검산",
    "86.14": "Theory 81의 same-event survivor floor 재사용; source premise",
    "86.15": "raw/fiber premise에서 normalized strict terminal로 가는 핵심 일부를 조건부 커널 검증",
    "86.16": "strict fiber gate에서 Theory-81 normalized gate로 가는 terminal을 조건부 커널 검증",
    "86.17": "disjoint support의 maximum-sum과 full residue energy 비교; Lean finite-set proof 대기",
    "86.18": "Theory 82 full residue energy upper 재사용; analytic premise 뒤 terminal만 부분 형식화",
    "86.19": "fiber route에서 Theory-82 full route로의 scalar refinement를 부분 형식화",
    "86.20": "finite nonempty fiber의 argmax 선택; Python fixture만 완료",
    "86.21": "abstract maximizing conditional law의 equality witness; Python exact 검산, Lean 대기",
    "87.1": "actual covering child의 a,b,k,kappa 정의",
    "87.2": "source atom·normalizer premise 뒤 nonempty atom cap의 monotonic terminal만 부분 형식화",
    "87.3": "retained vertex floor, covered fraction과 guaranteed nonempty count 정의",
    "87.4": "actual event-and-shift atom cap; Python finite chain 검산, Lean probability proof 대기",
    "87.5": "effective reciprocal atom denominator 정의",
    "87.6": "event atom과 full energy premise 뒤 raw-moment 합성 일부를 조건부 형식화",
    "87.7": "effective denominator character-energy gate에서 normalized strict gate로 조건부 커널 검증",
    "87.8": "effective/full primorial log premise 뒤 hierarchy만 부분 형식화",
    "87.9": "FGKMT proof normalizer 정의",
    "87.10": "Theory 54 quantitative good-normalizer floor; project analytic theorem은 Lean 미형식화",
    "87.11": "FGKMT formula (5.9) proof-constructed conditional law; Lean probability formalization 없음",
    "87.12": "Theory 53 full-residue edge-size cap source input",
    "87.13": "finite product survival floor; Lean finite-set product proof 대기",
    "87.14": "nonempty edge atom에서 vertex sparsity로의 source inclusion",
    "87.15": "source probability premise 뒤 atom upper의 scalar monotonicity를 조건부 커널 검증",
    "87.16": "한 nibble의 conditional product atom bound; Python chain-rule fixture 검산",
    "87.17": "adaptive stages의 chain-rule vector atom; global independence 없이 Python 검산",
    "87.18": "Theory 53 full-residue output equality와 deterministic lift",
    "87.19": "Theory 53 retained whole-set floor source transfer",
    "87.20": "Theory 55 covering-good whole-set survivor upper",
    "87.21": "coverage와 edge-size cap에서 real-valued nonempty count floor를 부분 형식화",
    "87.22": "integer ceiling 단계는 미형식화; division terminal만 재사용",
    "87.23": "t<=1/32, rho<=1/5에서 covered fraction 127/160을 조건부 커널 검증",
    "87.24": "event-shift atom과 full energy의 raw-moment 합성 일부를 형식화",
    "87.25": "Theory 82 full residue energy upper 재사용; analytic premise 뒤 terminal만 부분 형식화",
    "87.26": "effective denominator strict terminal의 핵심 일부를 형식화",
    "87.27": "strict character-energy input에서 Theory-81 normalized gate로 조건부 커널 검증",
    "87.28": "Theory 54 t0·kappa child source bounds; Lean analytic proof 없음",
    "87.29": "coordinate cap strictness의 all-parameter power bound; Python status guard, Lean 대기",
    "87.30": "Rosser-Schoenfeld theta upper의 outer product 적용; source theorem 미형식화",
    "87.31": "guaranteed K ceiling upper; Lean floor/ceil proof 대기",
    "87.32": "coordinate atom log identity·upper; real-log formalization 대기",
    "87.33": "minimum-count entropy gain upper; real-log formalization 대기",
    "87.34": "existing child의 four elementary scale inequalities; Lean 대기",
    "87.35": "rational coefficient 3823/512000<1/100만 독립 커널 검증",
    "87.36": "Dusart theta lower와 exceptional B0 전달; source theorem 미형식화",
    "87.37": "두 log premise에서 effective denominator가 primorial 아래임을 부분 형식화",
    "87.38": "Theory 83 favorable factor bounds 재사용",
    "87.39": "gate/effective/uniform envelope premise의 monotone hierarchy를 조건부 커널 검증",
    "87.40": "Theory 83 source-derived raw large-sieve lower certificate 재사용",
    "87.41": "세 envelope premise에서 raw certificate가 새 gate 위임을 조건부 커널 검증",
    "88.1": "outer와 dyadic-inner randomized support product 정의",
    "88.2": "FMT final-coordinate support cardinality; Python exact product fixture, Lean finite CRT proof 대기",
    "88.3": "sieve-good event-and-shift joint atom 정의",
    "88.4": "Theory 79·81의 sieve-good mass lower 재사용; source probability formalization 없음",
    "88.5": "finite support mass premise에서 maximum event atom lower를 조건부 커널 검증",
    "88.6": "valid atom cap의 success-mass entropy factor를 support로 조건부 커널 검증",
    "88.7": "support/full primorial log premise 뒤 strict hierarchy만 부분 형식화",
    "88.8": "FMT printed p.9 final residue extension source statement",
    "88.9": "FGKMT formula (5.9)의 good-history empty atom specialization; probability law 미형식화",
    "88.10": "checked source에 없는 uniform empty-atom target; OPEN 식",
    "88.11": "finite support sum 전체는 미형식화; 마지막 scalar pigeonhole만 부분 형식화",
    "88.12": "positive atom-cap division equivalence를 조건부 커널 검증",
    "88.13": "Rosser-Schoenfeld theta upper의 outer support 적용; source theorem 미형식화",
    "88.14": "outer support coefficient transfer; Lean real-log proof 없음",
    "88.15": "Theory 47 dyadic prime-count source/project theorem 재사용",
    "88.16": "P-prime subset cardinality 전달; finite-set proof 대기",
    "88.17": "a>=1000 scalar specialization; Lean 대기",
    "88.18": "inner support log product upper; finite prime-product proof 대기",
    "88.19": "support coefficient equality와 51/100 margin만 독립 커널 검증",
    "88.20": "Theory 87 Dusart full-primorial lower 재사용; source theorem 미형식화",
    "88.21": "두 log premise에서 strict support separation만 부분 형식화",
    "88.22": "atom/full-energy raw-moment 합성 일부를 기존 conditional terminal로 형식화",
    "88.23": "event atom-cap character-energy gate 정의",
    "88.24": "support/full envelope premises의 barrier hierarchy를 조건부 커널 검증",
    "88.25": "Theory 83 raw large-sieve source certificate 재사용",
    "88.26": "gate/support/full/RHS premise에서 insufficiency terminal을 조건부 커널 검증",
    "89.1": "fixed history local transform 정의",
    "89.2": "FGKMT formula (5.9)의 phase-weighted specialization; probability law Lean 미형식화",
    "89.3": "bad normalizer empty fallback의 local phase; source law 미형식화",
    "89.4": "same-stage conditional product identity; finite probability formalization 없음",
    "89.5": "randomized/fixed modulus CRT split 정의",
    "89.6": "randomized component가 principal인 blind character family 정의",
    "89.7": "fixed coordinates와 principal randomized factor의 coefficient identity; Lean 대기",
    "89.8": "finite character orthogonality의 blind total energy; Lean 독립증명 없음",
    "89.9": "total과 principal energy premise 뒤 nonprincipal subtraction을 조건부 커널 검증",
    "89.10": "FGKMT formula (5.9) source statement 재사용",
    "89.11": "global product를 금지하는 scope 경고; 정리 승격 대상 아님",
    "89.12": "quadratic level-set character values는 Python exact 검산; Lean은 산술 일부만",
    "89.13": "five atoms 1/5의 transform-one 산술을 부분 커널 검증",
    "89.14": "GKM Theorem 1.5의 source object; analytic theorem Lean 미형식화",
    "89.15": "GKM exceptional branch의 printed range; source theorem 미형식화",
    "89.16": "FMT final fixed-coordinate congruence source statement",
    "89.17": "full/randomized log premise에서 fixed 47/100 gap을 조건부 커널 검증",
    "89.18": "elementary exponential-vs-polynomial bound; Lean 대기",
    "89.19": "offset interval/fixed modulus distinctness transfer; Lean 대기",
    "89.20": "CRT character factorization과 fixed-shift identity; Lean 대기",
    "89.21": "finite character orthogonality source theorem; Lean 독립증명 없음",
    "89.22": "blind prime-error energy 정의",
    "89.23": "blind weighted contribution 정의",
    "89.24": "Cauchy premise 뒤 strict-gate terminal 일부만 형식화",
    "89.25": "blind energy strict upper에서 allocated weighted target으로 조건부 커널 검증",
    "90.1": "fixed/randomized modulus와 lifted character 정의",
    "90.2": "prime scale U와 d range 정의",
    "90.3": "native/lifted nonprincipal von Mangoldt sum 정의",
    "90.4": "finite removal identity premise 뒤 subtraction bookkeeping을 조건부 커널 검증",
    "90.5": "randomized-prime prime-power correction 정의",
    "90.6": "prime-power count와 triangle upper; Lean finite sum proof 대기",
    "90.7": "blind/native character energy 정의",
    "90.8": "complex square split의 characterwise 합; Python scalar fixture, Lean 대기",
    "90.9": "effective fixed-modulus exponent 정의",
    "90.10": "전체 range 중 endpoint 19530/47<416 산술만 부분 커널 검증",
    "90.11": "한 prime의 prime-power correction bound; Lean floor/log proof 대기",
    "90.12": "complex Young square inequality; Lean 독립증명 없음",
    "90.13": "uniform blind target 정의",
    "90.14": "eta=1 transfer premise와 두 quarter budget의 strict 합성을 조건부 커널 검증",
    "90.15": "denominator-cleared correction condition에서 quarter target을 조건부 커널 검증",
    "90.16": "favorable elementary correction sufficient gate; Lean 대기",
    "90.17": "Theory 89 fixed-modulus log lower 재사용",
    "90.18": "theta upper source theorem; Lean 미형식화",
    "90.19": "ratio derivation은 미형식화, endpoint rational만 부분 형식화",
    "90.20": "Bennett source cutoff lower 재사용; analytic theorem 미형식화",
    "90.21": "d_f<416 premise에서 900 cutoff no-overlap을 조건부 커널 검증",
    "90.22": "Vaughan fixed-A necessary range algebra; Lean 대기",
    "90.23": "Vaughan GRH source range; analytic theorem 미형식화",
    "90.24": "Vaughan finite centering/Parseval identity의 modulus-f 재사용; Lean 독립증명 없음",
    "90.25": "variance bridge identity·principal premise 뒤 strict transfer를 조건부 커널 검증",
    "90.26": "native quarter-gate favorable envelope; Lean 대기",
    "90.27": "Theory 83 raw large-sieve source lower를 modulus f에 재사용",
    "91.1": "fixed complex-weighted survivor sum 정의",
    "91.2": "single·pair survival probability 정의",
    "91.3": "finite complex second-moment identity; Python exact fixture, Lean finite-sum proof 대기",
    "91.4": "entrywise single·pair error 가정 정의",
    "91.5": "moment expansion·entrywise upper를 premise로 받은 scalar terminal과 l1-to-l2 loss를 조건부 커널 검증",
    "91.6": "project lower inputs를 premise로 beta*rho*M>1 terminal을 조건부 커널 검증",
    "91.7": "indicator square를 쓴 complex expansion; Lean finite-sum proof 대기",
    "91.8": "ideal rank-one pair term 분리; Lean complex finite-sum proof 대기",
    "91.9": "single-probability diagonal upper; Lean 독립증명 대기",
    "91.10": "entrywise pair error의 l1 expression에서 l2 loss로 가는 부분을 조건부 커널 검증",
    "91.11": "finite Cauchy l1-to-l2 입력; Lean finite-sum specialization 대기",
    "91.12": "common-shock pair 확률의 rational arithmetic만 부분 커널 검증",
    "91.13": "common-shock exact moment는 Python 전수, Lean은 결론 rational 값만 부분 검증",
    "91.14": "common-shock excess와 beta*rho^2*M(M-1) equality의 rational arithmetic을 부분 커널 검증",
    "91.15": "FGKMT rho·beta parameter 정의",
    "91.16": "exponential lower를 쓴 beta lower; analytic derivation 미형식화",
    "91.17": "m upper에서 rho lower로 가는 지수 부등식 미형식화",
    "91.18": "Theory 53 retained-vertex floor 재사용; source probability theorem 미형식화",
    "91.19": "project analytic lower를 premise로 spectral-loss terminal을 조건부 커널 검증",
    "91.20": "blind prime-error vertex weight와 survivor sum 정의",
    "91.21": "필요한 deterministic mean·L2 analytic inputs 정의",
    "91.22": "Gould--Kelly weighted matching source 조건; Lean 미형식화",
    "92.1": "fixed/randomized modulus와 blind lifted character 정의",
    "92.2": "lifted residue prime mass와 principal total 정의",
    "92.3": "blind nonprincipal inverse-transform weight 정의",
    "92.4": "finite character inverse transform; Python modulo-5 exact fixture, Lean finite-character proof 대기",
    "92.5": "selected sparse residue mean identity; Python finite fixture, Lean finite-sum proof 대기",
    "92.6": "analytic source bounds를 premise로 real discrepancy 11/5 terminal만 부분 커널 검증",
    "92.7": "mean·pointwise moment premises 뒤 success-scale normalization을 조건부 커널 검증",
    "92.8": "normalized finite pair factor 정의",
    "92.9": "full finite character orthogonality inverse transform; Lean 미형식화",
    "92.10": "full reduced-residue Parseval source identity; Lean 미형식화",
    "92.11": "Montgomery--Vaughan 1973 Theorem 2 source; Lean 미형식화",
    "92.12": "Brun--Titchmarsh에서 theta upper로의 전달; Lean 미형식화",
    "92.13": "d_f>=21 monotonicity 중 endpoint 21/10 산술만 부분 커널 검증",
    "92.14": "elementary global prime-power bound; Lean finite prime-power proof 대기",
    "92.15": "progression mass upper 합성; analytic source premise 미형식화",
    "92.16": "Rosser--Schoenfeld theta source와 prime-power 합성; Lean 미형식화",
    "92.17": "두 elementary correction gate 정의",
    "92.18": "nonnegative progression/principal upper premise에서 11/5 discrepancy terminal을 부분 커널 검증",
    "92.19": "pointwise envelope의 selected-set L2 합; Lean finite-sum proof 대기",
    "92.20": "Theory 91 pair coefficient 재정의",
    "92.21": "mean·L2 premise 뒤 normalized moment scalar 합성을 조건부 커널 검증",
    "92.22": "Gamma_M-beta exact finite-size correction을 비영 분모 premise 아래 조건부 커널 검증",
    "92.23": "inner success-event survivor floor interface 정의; source probability theorem 미형식화",
    "92.24": "strict normalized certificate에서 raw success-scale target으로 조건부 커널 검증",
    "92.25": "construction-dependent sparse centered mean root gate 정의",
    "93.1": "fixed prime vertex set과 cardinality 정의",
    "93.2": "outer survival indicator 정의",
    "93.3": "Theory 49 exact single·pair survival source 입력; Lean 미형식화",
    "93.4": "fixed Q-prime mean과 random weighted sum 정의",
    "93.5": "weighted expectation identity를 premise로 fixed mean persistence terminal을 부분 커널 검증",
    "93.6": "weighted covariance expansion과 entrywise pair-error upper; Lean은 component 합성만 조건부 검증",
    "93.7": "L-infinity normalized variance upper; finite-sum·division 전체 Lean proof 대기",
    "93.8": "count-good·adaptive deletion event parameter 정의",
    "93.9": "fixed Q-prime mean ratio 정의",
    "93.10": "selected-mean numerator·denominator transfer를 조건부 scalar terminal로 검증",
    "93.11": "deterministic fixed Q-prime analytic root gate 정의",
    "93.12": "Theory 92 inverse-transform weight 재사용; finite character source 미형식화",
    "93.13": "weighted expectation finite sum; identity premise 뒤 zero terminal만 부분 검증",
    "93.14": "weighted variance exact expansion; Lean finite probability proof 대기",
    "93.15": "ordered covariance triangle upper; Lean finite sum proof 대기",
    "93.16": "pointwise L-infinity에서 l1/l2 finite-sum upper; Lean 대기",
    "93.17": "Chebyshev weighted fluctuation failure; probability theorem 미형식화",
    "93.18": "Theory 51 deterministic expectation lower; source theorem 미형식화",
    "93.19": "project fluctuation failure 합성; Lean analytic inequality proof 대기",
    "93.20": "Theory 51 whole-interval count-good source theorem; Lean 미형식화",
    "93.21": "selected-count lower; b=2000 positive endpoint만 부분 커널 검증",
    "93.22": "adaptive deletion numerator와 cross-multiplied ratio를 조건부 커널 검증",
    "93.23": "preparation failure budget 정의",
    "93.24": "union mass premise 뒤 scalar terminal만 조건부 커널 검증",
    "93.25": "fixed Q-prime shifted-pair expansion 정의",
    "94.1": "centered residue kernel 정의",
    "94.2": "selected Q-prime summed kernel 정의",
    "94.3": "finite sum exchange로 얻는 fixed mean kernel identity; Lean finite-sum proof 대기",
    "94.4": "full reduced residue kernel의 mean-zero scalar arithmetic을 부분 커널 검증",
    "94.5": "prime·higher-prime-power split premise 뒤 subtraction terminal을 조건부 커널 검증",
    "94.6": "prime component 정의",
    "94.7": "higher-prime-power component 정의",
    "94.8": "B0 atom decomposition premise 뒤 centered bookkeeping을 조건부 커널 검증",
    "94.9": "p>X centered prime component 정의",
    "94.10": "positive congruent prime-pair mass 정의",
    "94.11": "unique residue reindex premise 뒤 centered binary-prime scalar bookkeeping을 조건부 커널 검증",
    "94.12": "prime-power correction analytic envelope; Lean finite prime-power proof 대기",
    "94.13": "B0 relative correction; Lean log monotonicity proof 대기",
    "94.14": "centered binary-prime target ratio 정의",
    "94.15": "Theory 92 inverse-transform identity 재사용; finite character source 미형식화",
    "94.16": "two-valued selected kernel envelope; Lean finite set proof 대기",
    "94.17": "global higher-prime-power mass upper; Lean finite prime proof 대기",
    "94.18": "explicit exponential correction envelope와 monotonicity; Lean 대기",
    "94.19": "relative correction component premise 뒤 downstream transfer를 조건부 커널 검증",
    "94.20": "Sono Assumption UB와 Halberstam--Richert source theorem; Lean 미형식화",
    "94.21": "hypothetical one-sided pair upper interface; analytic source 미형식화",
    "94.22": "zero pair mass가 one-sided upper를 만족하면서 relative centered error 1인 countermodel을 부분 커널 검증",
    "95.1": "Theory 94 centered prime core 재사용",
    "95.2": "finite nonprincipal character orthogonality source identity; Lean 미형식화",
    "95.3": "small-prime coefficient와 large-prime error 정의",
    "95.4": "character dual identity premise 뒤 conductor representation과의 equality를 조건부 커널 검증",
    "95.5": "unique primitive conductor induction premise 뒤 dual bookkeeping을 조건부 커널 검증",
    "95.6": "conductor-level small-prime coefficient energy 정의",
    "95.7": "primitive character orthogonality와 divisor Möbius inversion; Python exact fixture, Lean 미형식화",
    "95.8": "all-minus-principal energy terminal을 조건부 커널 검증",
    "95.9": "large-prime primitive conductor energy 정의",
    "95.10": "separate Cauchy certificate; analytic finite-sum proof Lean 대기",
    "95.11": "optimistic separate-L2 normalized square를 비영 분모 premise 아래 조건부 커널 검증",
    "95.12": "induced/primitive character value equality on f-coprime primes; Lean 미형식화",
    "95.13": "all-character residue occupancy energy; Lean finite character proof 대기",
    "95.14": "Schlage--Puchta Theorem 2 source; exponent margin 3<21만 부분 커널 검증",
    "95.15": "theta source를 쓴 prime log-square mass upper; Lean 미형식화",
    "95.16": "prime-supported large-sieve source 합성; implicit multiplier로 미형식화",
    "95.17": "project phi(f)>2N scale lower; analytic Mertens inputs 미형식화",
    "95.18": "phi>2N premise에서 optimistic normalized certificate>1을 조건부 커널 검증",
    "95.19": "small-prime full-modulus source necessary range 정의",
    "95.20": "cubefree single-character low-conductor range source; Lean 미형식화",
    "95.21": "separate conductor energy product architecture 정의",
    "95.22": "required direct signed weighted-product gate 정의",
    "96.1": "prime-supported character theta sum 정의",
    "96.2": "half-open small-prime coefficient 정의",
    "96.3": "Stieltjes/Abel endpoint identity; Python finite analogue, Lean analytic proof 미형식화",
    "96.4": "large-prime theta increment 정의",
    "96.5": "two-scale character covariance 정의",
    "96.6": "characterwise Abel premise 뒤 weighted-product bookkeeping을 조건부 커널 검증",
    "96.7": "fixed-modulus residue prime error 정의",
    "96.8": "character/residue cross-covariance orthogonality; Python exact fixture, Lean source 미형식화",
    "96.9": "required uniform cross-covariance input 정의",
    "96.10": "endpoint와 integral upper premises 뒤 Abel multiplier 합성을 조건부 커널 검증",
    "96.11": "project log-log ratio upper; analytic log inequality Lean 대기",
    "96.12": "ratio premise 뒤 project multiplier transfer와 rational fixture를 조건부/부분 커널 검증",
    "96.13": "reciprocal-log derivative source calculus; Lean 미형식화",
    "96.14": "Stieltjes integration-by-parts identity; Lean 미형식화",
    "96.15": "character inversion source identity; Lean 미형식화",
    "96.16": "character/residue covariance equality premise 뒤 zero terminal만 부분 검증",
    "96.17": "residue error norm 정의",
    "96.18": "real polarization scalar identity를 조건부 커널 검증",
    "96.19": "logarithmic integral evaluation; Lean calculus proof 대기",
    "97.1": "single large endpoint의 centered residue Linf norm 정의",
    "97.2": "lower endpoint one-atom correction 정의",
    "97.3": "endpoint subtraction triangle은 커널 검증; max와 scaling 전체는 부분형식화",
    "97.4": "nonnegative centered residue mass의 L1 upper; exact Python finite proof, Lean finite-sum proof 대기",
    "97.5": "L1-Linfinity cross envelope; Python exact fixture, Lean finite-sum proof 대기",
    "97.6": "Theory 47 project scale premises의 안전한 약화",
    "97.7": "B0<=X에서 Q-prime interval count identity; Lean finite-set proof 대기",
    "97.8": "Rosser--Schoenfeld source bounds 뒤 half-scale count terminal을 조건부 커널 검증",
    "97.9": "Rosser--Schoenfeld prime-count upper에서 theta upper로의 source-backed transfer; Lean 미형식화",
    "97.10": "small-scale mass ratio 21/10; source calculus와 log monotonicity Lean 대기",
    "97.11": "cross envelope와 21/10 premise에서 21/5 terminal을 조건부 커널 검증",
    "97.12": "endpoint epsilon에서 kappa=21/5 epsilon 합성을 조건부 커널 검증",
    "97.13": "Theory 96 Abel ratio premise 뒤 project multiplier와 rational fixture를 조건부/부분 커널 검증",
    "97.14": "f>X one-residue one-atom lower-endpoint bound; Lean finite residue proof 대기",
    "97.15": "phi(f)<=U^(1/21) correction envelope; real-power monotonicity Lean 대기",
    "97.16": "centered nonnegative vector L1 직접 부등식; Python exact fixture, Lean finite-sum proof 대기",
    "97.17": "Rosser--Schoenfeld Theorem 1 source prime-count 양측식",
    "97.18": "project Y/X premises에서 pi(X) half-budget으로의 elementary transfer; Lean 대기",
    "97.19": "Vaughan 1998 I Criterion-U source assumption",
    "97.20": "Vaughan 1998 I Theorem 1 source Q range",
    "97.21": "Vaughan 1998 II Criterion-U와 mean-square source assumptions",
    "97.22": "Vaughan 1998 II Theorems 1--2 source Q range",
    "97.23": "Harper 2024 dyadic variance와 source Q range",
    "97.24": "Thorner--Zaman hidden multiplier를 보존한 conditional endpoint diagnostic interface",
    "97.25": "fully numerical centered fixed-modulus endpoint target 정의",
    "98.1": "actual primorial, deleted modulus, native modulus와 effective exponent 정의",
    "98.2": "Sono Proposition 5.3의 direct t=0 nonexceptional zero-free source statement",
    "98.3": "Theory 90 log-f lower와 full primorial theta upper 재사용",
    "98.4": "project log ratio transfer; rational coefficient는 98.5와 함께 부분 커널 검증",
    "98.5": "c_ZFR=1/24와 47/105에서 c2=47/2520 rational terminal을 부분 커널 검증",
    "98.6": "Thorner--Zaman Remark 1.3 lambda=1, theta=7/12 source conclusion",
    "98.7": "d_f>=21에서 printed exponent 12 range endpoint을 부분 커널 검증",
    "98.8": "Vinogradov--Korobov decay scale 정의",
    "98.9": "미인쇄 K_TZ,c_TZ를 보존한 full-interval source-error interface 정의",
    "98.10": "fully numerical full-interval pointwise target; source constants OPEN",
    "98.11": "reduced residues 합으로 얻는 total endpoint error; Lean finite-sum proof 대기",
    "98.12": "common-main pointwise와 mean error에서 centered factor 2를 조건부 커널 검증",
    "98.13": "Theory 97 endpoint multiplier 합성과 exact rational fixture를 조건부/부분 커널 검증",
    "98.14": "FMT/Sono actual exceptional-prime choice source statement",
    "98.15": "Sono Proposition 5.3 direct zero-free source formula",
    "98.16": "Thorner--Zaman full-interval exceptional secondary main 정의",
    "98.17": "mean-zero real character pattern이 centering 뒤 남는 scalar fixture를 부분 커널 검증",
    "98.18": "Thorner--Zaman Corollary 1.4 full-interval source statement",
    "98.19": "common-main residue error와 mean error 정의",
    "98.20": "pointwise error에서 mean error upper; Lean finite-sum proof 대기",
    "98.21": "centered triangle factor 2를 조건부 커널 검증",
    "99.1": "Thorner--Zaman explicit density Theorem 1.2 source statement",
    "99.2": "fixed conductor-height family를 explicit modulus-height box에 포함하는 source transfer",
    "99.3": "density exponent 99와 theta=98/99 정의",
    "99.4": "proof sigma lower의 rational endpoint 98/99>39/40을 부분 커널 검증",
    "99.5": "full-interval main-size sufficient epsilon range 정의",
    "99.6": "d_f<416의 epsilon ceiling exact rational을 부분 커널 검증",
    "99.7": "explicit McCurley zero-free constant source 정의",
    "99.8": "available standard zero-free width 정의",
    "99.9": "Theorem 2.3 direct sup certificate 정의",
    "99.10": "source range endpoint 대입 뒤 positive sup-interval margin identity를 부분 커널 검증",
    "99.11": "t=e에서 sup lower; exp와 Euler constant inequalities Lean 미형식화",
    "99.12": "current envelope의 decay exponent exact rational과 <3/1000을 커널 검증",
    "99.13": "exp(-x)>1-x와 e<4 source calculus 합성; Lean 대기",
    "99.14": "optimistic multiplier-one floor의 exact rational과 >49를 커널 검증",
    "99.15": "phi(f)<=f에서 full-interval main-size lower; Lean arithmetic-function proof 대기",
    "99.16": "t=e decay exponent 전개; real log identity Lean 대기",
    "100.1": "fixed-f source parameters Q=f,T=f^5,D=f^7 정의",
    "100.2": "Theory 71 primitive near-one averaged density source statement",
    "100.3": "Theory 71 detector scale와 local-width 정의",
    "100.4": "baseline C_J density coefficient 정의",
    "100.5": "fixed-f prime scale의 kappa와 lambda 정의",
    "100.6": "omega=1/21에서 kappa=22 exact rational을 부분 커널 검증",
    "100.7": "explicit McCurley zero-free source constant 정의",
    "100.8": "near-integral favorable decay shape; analytic source transfer 미형식화",
    "100.9": "Theory 73 finite-safe tightened coefficient source value",
    "100.10": "d_f<416의 tightened decay exponent <9를 커널 검증",
    "100.11": "tightened coefficient/3^9 rational floor는 커널 검증; exp(-x)>3^-9는 Lean 대기",
    "100.12": "theta^-6 architecture coefficient floor 정의",
    "100.13": "kappa>=14 counterfactual decay exponent rational과 <9를 커널 검증",
    "100.14": "21^6/3^9 exact floor와 >4000은 커널 검증; exp source inequality는 부분형식화",
    "101.1": "Theory 95 small-prime coefficient와 large-prime packet 재사용 정의",
    "101.2": "finite nonprincipal weighted-product identity 재사용",
    "101.3": "truncated nonexceptional zero packet 정의",
    "101.4": "characterwise explicit-formula interface; analytic theorem 미형식화",
    "101.5": "weighted product의 signed zero-packet와 correction 분해 정의",
    "101.6": "joint zero correlation과 correction 정의",
    "101.7": "phase-blind triangle upper; finite complex proof Lean 대기",
    "101.8": "real subspace phase-alignment equality fixture를 부분 커널 검증",
    "101.9": "coefficient와 packet energies 정의",
    "101.10": "joint angle 정의",
    "101.11": "Cauchy angle range; finite complex proof Lean 대기",
    "101.12": "Theory 95 exact coefficient energy 재사용",
    "101.13": "optimistic packet-energy premise 뒤 normalized joint-angle terminal 정의",
    "101.14": "conditional energy upper의 sufficient squared-angle budget; actual target의 필요조건은 아님",
    "101.15": "squared-angle rational fixture를 커널 검증",
    "101.16": "same-magnitude aligned/cancelling packet fixture 정의",
    "101.17": "same-magnitude correlations 2와 0을 부분 커널 검증",
    "101.18": "Motohashi auxiliary-modulus character square moment source statement",
    "101.19": "Zheng simultaneous-AP well-factorable mean-value source statement",
    "101.20": "Szabo/Heath-Brown bounded-order single-character real-part source statement",
    "102.1": "finite centered residue mask 정의",
    "102.2": "임의 finite subset의 centered mask 합 0과 complex coercion을 커널 검증",
    "102.3": "canonical prime-power congruence와 closed endpoint 정의",
    "102.4": "corrected standard explicit-formula interface; numerical K_EF 및 analytic source 미형식화",
    "102.5": "possible real zero를 포함한 all-zero endpoint packet 정의",
    "102.6": "공통 convention의 regularizer 상쇄를 complex ring 대수로 커널 검증",
    "102.7": "generic finite endpoint replay·sum exchange만 검증; actual character/prime-power identification 미형식화",
    "102.8": "임의 complex constant channel의 centered projection 0을 커널 검증",
    "102.9": "possible distinguished real-zero term 보존; analytic zero convention 미형식화",
    "102.10": "source psi remainder shape 정의; hidden multiplier를 숫자 1로 치환하지 않음",
    "102.11": "임의 finite mask의 full L1 mass 2*N*(phi-N)를 커널 검증",
    "102.12": "uniform complex error norm premise에서 interval projection bound를 조건부 커널 검증",
    "102.13": "source error-shape monotonicity·normalization 문서 증명; Lean 대기",
    "102.14": "elementary global higher-prime-power bound 문서 증명; Lean 대기",
    "102.15": "symbolic f^s height의 remainder 전개; real power 합성 미형식화",
    "102.16": "T=f^(3/2) parameterized decay; real log/exp 전체 미형식화",
    "102.17": "uniform rational coefficient 699716을 커널 검증; actual f/U 계산 아님",
    "102.18": "log f>=64 polynomial absorption 문서 증명; real calculus Lean 대기",
    "102.19": "K_EF 보존 symbolic cutoff; numerical X_cert/range certificate 아님",
    "102.20": "rational kappa_3/2=11·kappa_5=22만 커널 검증; density transfer OPEN",
    "103.1": "fixed ft versus generic averaged f^2t scale 정의; log specialization만 커널 검증",
    "103.2": "동일 f의 약수 conductor 쌍의 lcm divisibility와 <=f를 커널 검증",
    "103.3": "Theory 64 fixed-modulus detector의 실제 source 재사용; analytic identification 미형식화",
    "103.4": "theta=1/21 power-condition equality margin을 기존 polynomial theorem으로 커널 검증",
    "103.5": "모든 local height를 덮는 source common cutoff 정의; numeric X cutoff 평가 아님",
    "103.6": "exp(22/21)*(442/441)<3만 커널 검증; Rankin/Euler source 전체는 부분형식화",
    "103.7": "all-height source factor의 rational coefficient composition과 <5e10를 커널 검증",
    "103.8": "source-premise fixed-modulus near-one density 재합성; source 전체 미형식화",
    "103.9": "fixed-scale kappa endpoints 55/7·22/7만 커널 검증",
    "103.10": "McCurley product zero-free source; one real exception 분리, source theorem 미형식화",
    "103.11": "actual B0 relative bound 재사용; real-zero 부재를 주장하지 않음",
    "103.12": "finite counting-measure exponential layer cake; integral Lean 대기",
    "103.13": "density polynomial envelope와 finite log absorption; Lean 합성 대기",
    "103.14": "endpoint-safe count integration과 nonpositive terminal coefficient; Lean 대기",
    "103.15": "normalized ratio rectangle과 scalar factor <=20만 커널 검증; analytic A(t) identification 부분형식화",
    "103.16": "finite reciprocal-height scalar decomposition만 커널 검증; counting integral identification 부분형식화",
    "103.17": "전체 w>=0 height cost의 field identity·inequality와 source-range premise를 커널 검증",
    "103.18": "weighted near integral와 actual zero-kernel bound; Lean 전체 형식화 대기",
    "103.19": "Bennett total-count far branch와 rho=0-safe kernel 합성; Lean 대기",
    "103.20": "actual X<f lower near packet의 vanishing bound; Lean 대기",
    "103.21": "possible real-zero term의 explicit B0 upper; absence 가정 없음, Lean 대기",
    "103.22": "전체 centered binary source-premise composition; actual same-law root 미완료",
    "103.23": "고정 d333 sufficient regime의 exact rational exponent·budget 비교를 커널 검증",
    "103.24": "displayed real-exponential nonvanishing kernel <1/100을 커널 검증; 실제 d_f>=333 확인은 아님",
    "103.25": "source/scale와 vanishing budget을 explicit premise로 받는 final 1/50 allocation 대수",
    "104.1": "actual raw primes와 lower/S set 정의; outcome-good subset과 구별",
    "104.2": "actual potential-coordinate products q,h,f 정의",
    "104.3": "full finite product q=h*f를 커널 검증; quotient/source assignment는 부분형식화",
    "104.4": "native product의 lower product divisibility만 커널 검증; theta log identification 부분형식화",
    "104.5": "B0 위치를 포함한 exact finite product identity; real log identification 부분형식화",
    "104.6": "actual power cutoff 정의와 rho<=1/4의 log inequality를 커널 검증",
    "104.7": "전체 power/exponential cap <=X/512를 커널 검증; source X=e^a mapping 부분형식화",
    "104.8": "exponential cubic lower와 a^2<=e^a·a/e^a<=1/a를 커널 검증",
    "104.9": "RS theta lower와 product-log source premise의 actual q coefficient를 조건부 커널 검증",
    "104.10": "raw inner count·theta source upper를 받은 support coefficient를 조건부 커널 검증",
    "104.11": "strong native lower의 full field transfer만 검증; theta/product log와 upper 전체는 부분형식화",
    "104.12": "actual source log bounds에서 D=160 native lower를 조건부 커널 검증",
    "104.13": "actual strong log bounds에서 native upper<323<333을 조건부 커널 검증",
    "104.14": "actual log f>30000만 검증; source cutoff component assembly는 부분형식화",
    "104.15": "full-primorial quotient decay와 rational >6를 검증; B0 analytic gap 연결 부분형식화",
    "104.16": "actual baseline d314의 exact exponent comparisons를 커널 검증",
    "104.17": "baseline rational nonvanishing budget <1/36를 커널 검증",
    "104.18": "displayed baseline real-exponential kernel <1/36를 커널 검증; actual error 관측 아님",
    "104.19": "height-weighted density·EF·prime-power의 whole source composition; analytic source 미형식화",
    "104.20": "actual native d>=314에서 full vanishing shape domination을 커널 검증",
    "104.21": "whole ell>=64 polynomial/exponential absorption을 커널 검증",
    "104.22": "positive unknown K coefficient와 symbolic log gate에서 vanishing allocation을 조건부 검증",
    "104.23": "actual analytic upper premises를 받은 total 3% allocation 대수; full same-law root 아님",
    "105.1": "LW Section3 source 계약 정의; 실제 t>=1,z=q*t만 사용",
    "105.2": "LW fixed all-character nontrivial zero-count 정의; multiplicity 포함",
    "105.3": "source free parameters와 actual large-log domain 정의",
    "105.4": "actual sqrt5 Stechkin coefficient의 rational enclosure를 커널 검증",
    "105.5": "source (3.22) A,B,C 정의; printed table 숫자는 미채택",
    "105.6": "전체 L>=30000의 scalar envelope를 커널 검증",
    "105.7": "source 분모 두 조건·exact lower 2221/15625·분자 9 상계를 커널 검증",
    "105.8": "source analytic floor count를 명시 premise로 받는 quotient/floor terminal 조건부 검증",
    "105.9": "safe scalar 144를 검증; Dirichlet count와 source equation identification은 부분형식화",
    "105.10": "local numerical floor<=2만 검증; source spacing·multiplicity·alternating sequence는 미형식화",
    "105.11": "McCurley/first-window split의 zero-width/height 영역; 전체 analytic mapping 미형식화",
    "105.12": "nonprincipal 누적 zero-count의 layer-cake identity; counting measure 적분 미형식화",
    "105.13": "first-window 내부 count 적분 bound; moving zero class로 바꾸지 않음",
    "105.14": "Theory103 fixed nonprincipal source density tail 재사용; principal 포함하지 않음",
    "105.15": "normalized ratios와 tail factor24만 검증; count 적분과 upper endpoint 합성은 부분형식화",
    "105.16": "low-height packet을 보존한 height layer cake; analytic identity 미형식화",
    "105.17": "전체 height domain의 exact field identity와 4/5 decay를 커널 검증",
    "105.18": "height allocation과 inverse-rho scalar coefficients만 검증; actual zero-error identification 미형식화",
    "105.19": "realDecay>=6에서 displayed real exponential kernel<3/1000를 커널 검증; PNT/EF/root 인증 아님",
    "62.1": "Jutila 식 (2.11)의 source Mellin identity; complex analytic theorem은 Lean 미형식화",
    "62.2": "우측 contour line 선택; residue·수평변 complex analysis는 Lean 미형식화",
    "62.3": "actual M bound의 두 local 실수부등식만 커널 검증; 전체 character polynomial은 미형식화",
    "62.4": "n/phi(n) 합과 Euler-product multiplier 3은 문서·exact Python 검산; Lean 부분형식화",
    "62.5": "4/sqrt(6) 보정의 제곱 유리값만 커널 검증; primitive 유도식은 미형식화",
    "62.6": "Bennett et al. Lemma 5.6 (5.3)의 Rademacher convexity source theorem",
    "62.7": "vertical L bound 중 real triangle budget만 커널 검증",
    "62.8": "Gamma recurrence·integral에서 얻는 pointwise source/direct-proof bound",
    "62.9": "Gamma 적분 split의 유한 계수 합성만 커널 검증",
    "62.10": "직접 Mellin 상수 합성은 문서·100-dps Python 검산; full complex integral 미형식화",
    "62.11": "delta_epsilon 정의와 0<delta<1/4를 커널 검증",
    "62.12": "alpha>=1/2, beta>=alpha에서 exponent <=-epsilon/2를 커널 검증",
    "62.13": "source power condition에서 최종 real-power transfer; exponent만 커널 검증",
    "T63-U001": "Jutila의 finite cut 정의",
    "T63-U002": "actual D,R,X parameter 전사",
    "63.10": "actual tail 결론 중 exponent 합만 커널 검증; coefficient·무한합은 문서 직접 proof",
    "63.11": "0<eta<=4와 epsilon>0에서 max/sqrt cutoff의 tail-budget transfer 커널 검증",
    "63.1": "Jutila 식 (2.11)에서 분리한 tail 정의",
    "63.2": "divisor pairing과 actual pseudocharacter 점별 상계; 문서 proof·작은 Python 검산",
    "63.3": "beta>=1/2와 유한 r-count의 analytic 합성; Lean 순차 형식화 대기",
    "63.4": "첫 생략 정수 floor(x)+1의 geometric tail identity; Lean 순차 형식화 대기",
    "63.5": "exp(u)-1>=u에서 얻는 reciprocal bound를 커널 검증",
    "63.6": "reciprocal bound와 X+1<=2X는 커널 검증; 앞선 coefficient·tail 합성은 부분형식화",
    "63.7": "general upper-envelope 조건 정의",
    "63.8": "R,X upper envelope 이후 actual exponential bound; 문서·Python 검산",
    "63.9": "linear/quadratic cutoff에서 exponential budget으로 가는 실수대수 커널 검증",
    "63.12": "Jutila 인쇄 p.52 actual parameter 전사",
    "63.13": "actual exponent epsilon+(1+12epsilon)=1+13epsilon 커널 검증",
    "64.1": "Jutila 인쇄 p.52 actual parameter와 theta 범위 전사",
    "64.2": "네 positive loss 합과 source loss 사이 budget 정의",
    "64.3": "source analytic component를 premise로 받은 네 loss 종단 합성과 source coefficient 회복을 커널 검증",
    "64.4": "Jutila 식 (2.11)의 source detector identity; complex/Dirichlet identity 자체는 미형식화",
    "64.5": "source identity 이후 triangle 방향을 premise로 받은 종단 합성만 커널 검증",
    "64.6": "C_phi 정규화 정의",
    "64.7": "Zuniga Alterman source error와 Euler-product bridge 이후 lower transfer; analytic source는 미형식화",
    "64.8": "두 multiplicative loss가 additive sum 이하임을 커널 검증",
    "64.9": "Mellin·tail relative budget 목표 정의",
    "64.10": "actual A=D^(1+9theta) parameter 전사",
    "64.11": "0<=theta<=1/21의 exact exponent margin을 커널 검증",
    "64.12": "원래 log 조건의 square-root transfer; 문서 proof·Python 범위검사",
    "64.13": "Rosser--Schoenfeld Theorem 15과 small-q exact check의 source-backed 합성; source theorem 미형식화",
    "64.14": "64.13에서 C_phi inverse로 가는 대수는 문서 합성; source theorem 미형식화",
    "64.15": "Zuniga Alterman B_q 정의 전사",
    "64.16": "소인수 순서와 elementary integral bound의 직접 proof; Lean 순차 형식화 대기",
    "64.17": "finite Euler-product envelope의 직접 proof; Lean 순차 형식화 대기",
    "64.18": "root cutoff 전체는 미형식화; terminal exponent absorption만 커널 검증",
    "64.19": "B exponent premise 이후 negative exponent 흡수를 커널 검증",
    "64.20": "여덟 component sufficient cutoff 정의; exp/log implication은 문서·Python 검산",
    "64.21": "delta와 Mellin multiplier 정의 전사",
    "64.22": "theta=1/100 equal-split high-precision diagnostic; directed interval certificate 아님",
    "64.23": "theta=1/100 sufficient cutoff high-precision diagnostic; 최소 threshold 아님",
    "27.9": "원문 display 종료기호 누락; hash 보존",
    "27.10": "원문 display 종료기호 누락; hash 보존",
    "27.11": "원문 display 종료기호 누락; hash 보존",
    "27.12": "원문 display 종료기호 누락; hash 보존",
    "27.13": "원문 display 종료기호 누락; hash 보존",
}


def preview(latex: str, limit: int = 220) -> str:
    compact = " ".join(latex.split())
    if len(compact) > limit:
        compact = compact[: limit - 1] + "…"
    return html.escape(compact, quote=False).replace("|", "&#124;")


def doc_link(source_file: str) -> str:
    name = Path(source_file).name
    return f"[{name}](../{source_file})"


def build_ledger(inventory: dict[str, object], status_doc: dict[str, object]) -> str:
    status_by_id = {entry["formula_id"]: entry for entry in status_doc["formulae"]}
    default_status = status_doc["default_status"]
    formulae = inventory["formulae"]
    counts = Counter(
        status_by_id.get(item["formula_id"], {}).get("status", default_status)
        for item in formulae
    )
    reviewed_by_theory = Counter(
        item["theory"]
        for item in formulae
        if status_by_id.get(item["formula_id"], {}).get("status", default_status)
        != default_status
    )

    lines = [
        "# FGKMT-Sono Lean 전수 수식·정리 검증 원장",
        "",
        "- 생성 기준: 2026-09-14 KST",
        f"- inventory schema: `{inventory['schema_version']}`",
        f"- 원문 범위: `docs/method/theory/*.md` {inventory['theory_count']}개",
        f"- 전수 단위: Markdown fenced code 밖 display math {inventory['formula_count']:,}개",
        (
            f"- 원래 식번호: {inventory['tagged_formula_count']:,}개, 합성 ID 무번호식: "
            f"{inventory['untagged_formula_count']:,}개"
        ),
        f"- 안전 복구 표시: hash-pinned Theory 27의 누락 display 종료기호 {len(inventory['recoveries'])}개",
        "- 기계 정본: [formula_inventory_v1.json](verification/formula_inventory_v1.json)",
        "- 상태 정본: [verification_status_v1.json](verification/verification_status_v1.json)",
        "- Lean 정본: [TheoryVerification.lean](FGKMTSono/TheoryVerification.lean)",
        "- 현재 결론: 초기 dependency-critical batch만 형식화했다. 전체 Sono/FMT analytic theorem 또는",
        "  수치 `X_cert`가 Lean으로 증명됐다는 뜻이 아니다.",
        "",
        "## 1. 목적과 범위",
        "",
        "이 원장은 수식을 빠짐없이 식별하는 **전수 inventory**와 Lean이 실제 검사한 증거 수준을",
        "분리한다. inline math는 문장 안의 기호·매개변수 설명이므로 개별 proof obligation으로 세지",
        "않고, 모든 display math를 하나의 안정 항목으로 등록했다. 원래 `\\tag{...}`가 없는 display",
        "수식에는 `T<theory>-U<ordinal>` 합성 ID를 부여했다.",
        "",
        "원문 수식 자체는 각 source line과 SHA-256으로 고정한다. 표의 수식은 탐색용 preview이며,",
        "줄임 없는 LaTeX는 JSON inventory와 원문에 있다.",
        "",
        "## 2. 증거 수준",
        "",
        "| 상태 | 정확한 의미 |",
        "|---|---|",
    ]
    for status, meaning in STATUS_MEANING.items():
        lines.append(f"| `{status}` | {meaning} |")
    lines.extend(
        [
            "",
            "현재 `KERNEL_PASS`도 Lean/Mathlib의 표준 논리 기반 위의 검증이다. 외부 논문 명제를",
            "매개변수로 받은 정리는 반드시 `CONDITIONAL_KERNEL_PASS`로 낮춰 표시한다.",
            "",
            "## 3. 고정된 설치·dependency",
            "",
            "| 구성요소 | 고정값 | 검증 |",
            "|---|---|---|",
            "| Elan | 4.2.4, commit `227caca13` | 관측 |",
            "| Lean | `leanprover/lean4:v4.34.0-rc2` | `lean-toolchain` |",
            "| Lean kernel | `6a10ac8c22beadecabdbb0919c2b50214762f91d` | `lake env lean --version` |",
            "| Mathlib | `85e3a25e006c35636f0e53b0e9296caca2685bc0` | lakefile·manifest·local HEAD 3중 일치 |",
            "| transitive dependencies | `lake-manifest.json`의 full commit | manifest lock |",
            "",
            "## 4. 영향도와 검증 한계",
            "",
            "| 축 | 판정 |",
            "|---|---|",
            "| 반복로그·end-bounded 정의 | 정의를 Lean에 분리해 base-log 및 start/end 혼동을 방지 |",
            "| 유한 대수·floor·ceil·집합 논리 | Lean 독립 검증의 우선 대상 |",
            "| 적분·소수분포·sieve·hypergraph source theorem | Mathlib에 drop-in proof가 없으면 장기 source 형식화가 필요 |",
            "| 수치 근사 | exact rational theorem과 분리; decimal 출력만으로 PASS 금지 |",
            "| `X_cert` | DEP-R09–R12가 OPEN이므로 계속 OPEN |",
            "| actual experiment | 이번 원장은 새 prime 계산이나 `test_result`를 만들지 않음 |",
            "",
            "## 5. 현재 상태 집계",
            "",
            "| 상태 | 항목 수 |",
            "|---|---:|",
        ]
    )
    for status in STATUS_MEANING:
        lines.append(f"| `{status}` | {counts.get(status, 0):,} |")
    lines.extend(
        [
            "",
            "집계는 display 수식 행 기준이다. 하나의 Lean theorem이 여러 display 식의 합성을 검증하거나,",
            "한 display 식이 여러 Lean 선언으로 나뉠 수 있다.",
            "",
            "## 6. theory별 전수 현황",
            "",
            "| Theory | 원문 | SHA-256 | display | tagged | untagged | 현재 형식화·review 행 |",
            "|---:|---|---|---:|---:|---:|---:|",
        ]
    )
    for theory in inventory["theories"]:
        lines.append(
            f"| {theory['theory']} | {doc_link(theory['source_file'])} | "
            f"`{theory['source_sha256'][:16]}…` | {theory['display_formula_count']:,} | "
            f"{theory['tagged_formula_count']:,} | {theory['untagged_formula_count']:,} | "
            f"{reviewed_by_theory[theory['theory']]:,} |"
        )
    lines.extend(
        [
            "",
            "## 7. 추가 Lean 정리(문단 논증)",
            "",
            "| 원문 | Lean 선언 | 상태 | 범위 |",
            "|---|---|---|---|",
        ]
    )
    supplemental_scope = {
        "sequential_positive_probability_choice": "독립성이나 두 실패율 합 조건이 불필요하다는 순수 논리",
    }
    for item in status_doc.get("supplemental_theorems", []):
        declarations = "; ".join(f"`{name}`" for name in item["declarations"])
        scope = "; ".join(supplemental_scope.get(name, "보조 exact 정리") for name in item["declarations"])
        lines.append(f"| {item['source']} | {declarations} | `{item['status']}` | {scope} |")
    lines.extend(
        [
            "",
            "## 8. 수식별 전수 검증 표",
            "",
            "| # | 수식 ID | Theory·원문 | line | 수식 preview | Lean 선언 | 상태 | 한계·근거 |",
            "|---:|---|---|---:|---|---|---|---|",
        ]
    )
    for ordinal, item in enumerate(formulae, start=1):
        entry = status_by_id.get(item["formula_id"], {})
        status = entry.get("status", default_status)
        declarations = entry.get("declarations", [])
        declaration_text = "; ".join(declarations) if declarations else "—"
        if declarations:
            declaration_text = f"`{declaration_text}`"
        note = NOTES_BY_ID.get(
            item["formula_id"],
            "순차 형식화 대기" if status == default_status else STATUS_MEANING[status],
        )
        line_range = (
            str(item["start_line"])
            if item["start_line"] == item["end_line"]
            else f"{item['start_line']}–{item['end_line']}"
        )
        lines.append(
            f"| {ordinal} | `{item['formula_id']}` | T{item['theory']} "
            f"{doc_link(item['source_file'])} | {line_range} | "
            f"<code>{preview(item['latex'])}</code> | {declaration_text} | `{status}` | {note} |"
        )
    lines.extend(
        [
            "",
            "## 9. 발견된 원문·작업 오류",
            "",
            "1. hash-pinned Theory 27 식 (27.9)–(27.13)에 display 종료 `\\]` 5개가 빠져 있다.",
            "   원문 SHA 계약을 보존하기 위해 소급 변경하지 않고 inventory에서만 안전 분리했으며",
            "   다섯 행을 `PARSE_REVIEW_REQUIRED`로 남겼다.",
            "2. Theory 01 plateau 식의 `qquad` 앞 backslash 누락을 확인해 `\\qquad`로 교정했다.",
            "3. 단일 Lean target을 import한 뒤 target 생성 전에 최초 build를 시작해 한 차례",
            "   `no such file ... TheoryVerification.lean`이 발생했다. 작업 순서 오류로 기록하고",
            "   target 생성 뒤 직접 kernel 검사와 전체 build를 다시 수행한다.",
            "",
            "## 10. 순차 형식화 우선순위",
            "",
            "1. 초기 batch의 declaration–원장 연결과 no-sorry 검증을 고정한다.",
            "2. 현재 root DEP-R09의 exact source 진술과 finite-rate 의무를 먼저 고정한다.",
            "3. DEP-R09에서 실제 사용할 상수·부등식·endpoint 합성을 사용 전에 형식화한다.",
            "4. 이후 DEP-R10, R11, R12를 같은 source-first·역의존 순서로 처리한다.",
            "5. Theory 55의 잔여 source theorem과 Theories 10–11의 별도 finite-set 구조는",
            "   해당 DAG에서 다시 필요해질 때 독립 batch로 처리한다.",
            "6. 960개라는 총개수를 선행 gate로 쓰지 않는다. empirical·역사적·대체 식은 root-critical 식 뒤로 미룬다.",
            "7. source analytic theorem은 먼저 Mathlib/선행 형식화를 찾고, 없으면",
            "   `SOURCE_THEOREM_UNFORMALIZED`로 차단한 뒤 별도 장기 증명 단위로 분해한다.",
            "8. DEP-R09–R12와 end-to-end composition이 닫힌 뒤 비임계 잔여 coverage를 순차 처리한다.",
            "",
            "새 theory가 추가되면 inventory와 원장을 재생성하고 기존 source SHA가 움직였는지 먼저 검사한다.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
    )
    args = parser.parse_args()
    repo_root = args.repo_root.resolve()
    lean_root = repo_root / "lean"
    inventory = build_inventory(repo_root)
    if inventory["issues"]:
        raise ValueError(f"cannot generate from parse issues: {inventory['issues']}")
    status_path = lean_root / "verification" / "verification_status_v1.json"
    status_doc = json.loads(status_path.read_text(encoding="utf-8"))
    inventory_path = lean_root / "verification" / "formula_inventory_v1.json"
    ledger_path = lean_root / "VERIFICATION_LEDGER.md"
    inventory_path.write_text(
        json.dumps(inventory, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    ledger_path.write_text(
        build_ledger(inventory, status_doc),
        encoding="utf-8",
        newline="\n",
    )
    print(
        json.dumps(
            {
                "status": "GENERATED",
                "theory_count": inventory["theory_count"],
                "formula_count": inventory["formula_count"],
                "recoveries": len(inventory["recoveries"]),
            },
            ensure_ascii=True,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
