"""P012 log-x stratified conditional recurrence null model.

This module is an empirical diagnostic.  It conditions on the observed count
of each record-gap size inside fixed log10 bins and randomizes only its
positions inside each bin.  It does not assume that prime gaps are stationary,
independent, or generated by this null model.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np

from source.plateau_recurrence import KNOWN_PRIME_COUNTS, iter_prime_chunks
from source.provenance import require_experiment_approval, sha256_file
from source.recurrence_null_model import _bh_adjust


EXPERIMENT = "P012_P011_LOGX_STRATIFIED_CONDITIONAL_NULL"
SCHEMA_VERSION = "p012-stratified-hypergeometric-v1"
ANALYSIS_LIMIT = 1_000_000_000
DEFAULT_SEGMENT_SPAN = 50_000_000
DEFAULT_SEED = 20_260_827
DEFAULT_REPLICATIONS = 100_000
COMPLETE_PLATEAUS_SHA256 = (
    "4675e8b6e7284b31c61ad66f3f98ffa34114553d49ab32878c609608530daca6"
)
P011_STATISTICS_SHA256 = (
    "2fa3cfca10f83b91dd2f10310009370b2614549dee62d243b6f890b41ee5b302"
)
LOW_INFORMATION_MIN_CONDITIONED_GAPS = 5
LOW_INFORMATION_MIN_CONTROL_EXPOSURE = 1_000


class StratifiedNullError(ValueError):
    """Raised when a P012 input or fixed-design invariant fails."""


@dataclass(frozen=True, slots=True)
class BinScheme:
    name: str
    width: float
    shift: float


BIN_SCHEMES = (
    BinScheme("primary_width_0p5_shift_0", 0.5, 0.0),
    BinScheme("sensitivity_width_0p5_shift_0p25", 0.5, 0.25),
    BinScheme("sensitivity_width_1_shift_0p5", 1.0, 0.5),
)

COHORTS = (
    "primary_start_ge_1000",
    "all_eligible",
    "sensitivity_start_ge_100000",
)


def _write_json_exclusive(path: Path, payload: object) -> None:
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def _write_csv_exclusive(path: Path, rows: Sequence[dict[str, object]]) -> None:
    if not rows:
        raise StratifiedNullError(f"cannot write an empty table: {path.name}")
    with path.open("x", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def _load_plateaus(path: Path, *, require_pinned_hash: bool) -> list[dict[str, int]]:
    if require_pinned_hash and sha256_file(path) != COMPLETE_PLATEAUS_SHA256:
        raise StratifiedNullError("P006 complete-plateau input hash mismatch")
    with path.open("r", encoding="utf-8", newline="") as handle:
        raw_rows = list(csv.DictReader(handle))
    rows: list[dict[str, int]] = []
    for raw in raw_rows:
        row = {
            "record_index": int(raw["record_index"]),
            "start_prime": int(raw["start_prime"]),
            "gap": int(raw["gap"]),
            "right_exclusive": int(raw["start_exposure_right_exclusive"]),
            "N": int(raw["N"]),
            "M": int(raw["M"]),
            "C": int(raw["C"]),
        }
        if not (
            row["right_exclusive"] > row["start_prime"]
            and row["N"] >= row["M"] >= 1
            and row["C"] == row["M"] - 1
        ):
            raise StratifiedNullError("P006 plateau invariant failed")
        rows.append(row)
    if not rows:
        raise StratifiedNullError("P006 complete-plateau input is empty")
    for previous, current in zip(rows, rows[1:], strict=False):
        if previous["right_exclusive"] != current["start_prime"]:
            raise StratifiedNullError("complete plateau start-exposure intervals are not contiguous")
        if not current["gap"] > previous["gap"]:
            raise StratifiedNullError("record gaps are not strictly increasing")
    return rows


def _load_p011_statistics(
    path: Path, *, require_pinned_hash: bool
) -> dict[int, dict[str, float]]:
    if require_pinned_hash and sha256_file(path) != P011_STATISTICS_SHA256:
        raise StratifiedNullError("P011 plateau-statistics input hash mismatch")
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    result: dict[int, dict[str, float]] = {}
    for row in rows:
        record_index = int(row["record_index"])
        result[record_index] = {
            "p011_expected_recurrences": float(row["expected_recurrences"]),
            "p011_standardized_residual_z": float(row["standardized_residual_z"]),
        }
    if not result:
        raise StratifiedNullError("P011 plateau-statistics input is empty")
    return result


def _bin_indices(values: np.ndarray, scheme: BinScheme) -> np.ndarray:
    if np.any(values <= 0):
        raise StratifiedNullError("log-bin values must be positive")
    return np.floor((np.log10(values.astype(np.float64)) - scheme.shift) / scheme.width).astype(
        np.int64
    )


def _bin_bounds(index: int, scheme: BinScheme) -> tuple[float, float]:
    left = 10.0 ** (scheme.shift + scheme.width * index)
    right = 10.0 ** (scheme.shift + scheme.width * (index + 1))
    return left, right


def _increment_counts(target: dict[object, int], keys: np.ndarray) -> None:
    values, counts = np.unique(keys, return_counts=True, axis=0 if keys.ndim == 2 else None)
    if keys.ndim == 1:
        for value, count in zip(values, counts, strict=True):
            key: object = int(value)
            target[key] = target.get(key, 0) + int(count)
    else:
        for value, count in zip(values, counts, strict=True):
            key = tuple(int(item) for item in value)
            target[key] = target.get(key, 0) + int(count)


def accumulate_bin_counts(
    prime_chunks: Iterable[Sequence[int] | np.ndarray],
    plateaus: Sequence[dict[str, int]],
    *,
    schemes: Sequence[BinScheme] = BIN_SCHEMES,
) -> dict[str, object]:
    """Stream primes once and collect all fixed-bin sufficient statistics."""

    starts_left = np.asarray([row["start_prime"] for row in plateaus], dtype=np.int64)
    starts_right = np.asarray([row["right_exclusive"] for row in plateaus], dtype=np.int64)
    record_gaps = np.asarray([row["gap"] for row in plateaus], dtype=np.int64)
    target_gap_values = np.unique(record_gaps)
    populations = {scheme.name: {} for scheme in schemes}
    gap_counts = {scheme.name: {} for scheme in schemes}
    exposure_counts = {scheme.name: {} for scheme in schemes}
    exposure_equal_counts = {scheme.name: {} for scheme in schemes}
    previous_prime: int | None = None
    gap_count = 0
    prime_count = 0

    for raw_chunk in prime_chunks:
        chunk = np.asarray(raw_chunk, dtype=np.int64)
        if chunk.ndim != 1 or chunk.size == 0 or np.any(np.diff(chunk) <= 0):
            raise StratifiedNullError("prime chunks must be nonempty and strictly increasing")
        if previous_prime is not None and int(chunk[0]) <= previous_prime:
            raise StratifiedNullError("prime chunks overlap or are out of order")
        prime_count += int(chunk.size)
        paired = (
            chunk
            if previous_prime is None
            else np.concatenate((np.asarray([previous_prime], dtype=np.int64), chunk))
        )
        gaps = np.diff(paired)
        starts = paired[:-1]
        previous_prime = int(chunk[-1])
        if not gaps.size:
            continue
        gap_count += int(gaps.size)
        plateau_ids = np.searchsorted(starts_left, starts, side="right") - 1
        valid = plateau_ids >= 0
        valid &= starts < starts_right[np.clip(plateau_ids, 0, len(plateaus) - 1)]
        target_mask = np.isin(gaps, target_gap_values)
        equal_plateau_mask = valid & (gaps == record_gaps[np.clip(plateau_ids, 0, len(plateaus) - 1)])

        for scheme in schemes:
            bins = _bin_indices(starts, scheme)
            _increment_counts(populations[scheme.name], bins)
            if np.any(target_mask):
                _increment_counts(
                    gap_counts[scheme.name],
                    np.column_stack((bins[target_mask], gaps[target_mask])),
                )
            if np.any(valid):
                _increment_counts(
                    exposure_counts[scheme.name],
                    np.column_stack((plateau_ids[valid], bins[valid])),
                )
            if np.any(equal_plateau_mask):
                _increment_counts(
                    exposure_equal_counts[scheme.name],
                    np.column_stack(
                        (plateau_ids[equal_plateau_mask], bins[equal_plateau_mask])
                    ),
                )

    return {
        "prime_count": prime_count,
        "gap_count": gap_count,
        "populations": populations,
        "gap_counts": gap_counts,
        "exposure_counts": exposure_counts,
        "exposure_equal_counts": exposure_equal_counts,
    }


def build_components(
    plateaus: Sequence[dict[str, int]],
    accumulated: dict[str, object],
    *,
    schemes: Sequence[BinScheme] = BIN_SCHEMES,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    populations = accumulated["populations"]
    gap_counts = accumulated["gap_counts"]
    exposures = accumulated["exposure_counts"]
    exposure_equal = accumulated["exposure_equal_counts"]
    assert isinstance(populations, dict)
    assert isinstance(gap_counts, dict)
    assert isinstance(exposures, dict)
    assert isinstance(exposure_equal, dict)

    for scheme in schemes:
        scheme_pop = populations[scheme.name]
        scheme_gap = gap_counts[scheme.name]
        scheme_exp = exposures[scheme.name]
        scheme_equal = exposure_equal[scheme.name]
        assert isinstance(scheme_pop, dict)
        assert isinstance(scheme_gap, dict)
        assert isinstance(scheme_exp, dict)
        assert isinstance(scheme_equal, dict)
        for plateau_id, plateau in enumerate(plateaus):
            bins = sorted(
                bin_index
                for candidate_plateau, bin_index in scheme_exp
                if candidate_plateau == plateau_id
            )
            if not bins:
                raise StratifiedNullError("plateau has no log-bin exposure")
            forced_bin = int(
                _bin_indices(np.asarray([plateau["start_prime"]], dtype=np.int64), scheme)[0]
            )
            observed_sum = 0
            trials_sum = 0
            for bin_index in bins:
                forced = 1 if bin_index == forced_bin else 0
                population = int(scheme_pop.get(bin_index, 0)) - forced
                conditioned_gaps = int(scheme_gap.get((bin_index, plateau["gap"]), 0)) - forced
                exposure = int(scheme_exp.get((plateau_id, bin_index), 0)) - forced
                observed = int(scheme_equal.get((plateau_id, bin_index), 0)) - forced
                if not (
                    population >= exposure >= observed >= 0
                    and population >= conditioned_gaps >= observed
                ):
                    raise StratifiedNullError("forced-record removal violates hypergeometric counts")
                control = population - exposure
                expected = (
                    exposure * conditioned_gaps / population if population else 0.0
                )
                if population > 1:
                    probability = conditioned_gaps / population
                    variance = (
                        exposure
                        * probability
                        * (1.0 - probability)
                        * (population - exposure)
                        / (population - 1)
                    )
                else:
                    variance = 0.0
                left, right = _bin_bounds(bin_index, scheme)
                low_information = (
                    conditioned_gaps < LOW_INFORMATION_MIN_CONDITIONED_GAPS
                    or control < LOW_INFORMATION_MIN_CONTROL_EXPOSURE
                )
                rows.append(
                    {
                        "scheme": scheme.name,
                        "record_index": plateau["record_index"],
                        "start_prime": plateau["start_prime"],
                        "gap": plateau["gap"],
                        "bin_index": bin_index,
                        "bin_left": left,
                        "bin_right_exclusive": right,
                        "forced_record_removed": forced,
                        "population_after_removal": population,
                        "conditioned_gap_count_after_removal": conditioned_gaps,
                        "plateau_exposure_after_removal": exposure,
                        "observed_recurrences": observed,
                        "control_exposure": control,
                        "expected_component": expected,
                        "variance_component": variance,
                        "information_flag": "LOW_INFORMATION" if low_information else "OK",
                    }
                )
                observed_sum += observed
                trials_sum += exposure
            if observed_sum != plateau["C"] or trials_sum != plateau["N"] - 1:
                raise StratifiedNullError("binned components disagree with P006 N/M/C")
    return rows


def _cohorts_for_plateau(plateau: dict[str, int]) -> list[str]:
    cohorts = ["all_eligible"]
    if plateau["start_prime"] >= 1_000:
        cohorts.append("primary_start_ge_1000")
    if plateau["start_prime"] >= 100_000:
        cohorts.append("sensitivity_start_ge_100000")
    return cohorts


def analyze_components(
    plateaus: Sequence[dict[str, int]],
    components: Sequence[dict[str, object]],
    p011_statistics: dict[int, dict[str, float]],
    *,
    replications: int = DEFAULT_REPLICATIONS,
    seed: int = DEFAULT_SEED,
    schemes: Sequence[BinScheme] = BIN_SCHEMES,
) -> dict[str, object]:
    if replications < 1_000:
        raise StratifiedNullError("at least 1,000 Monte Carlo replications are required")
    by_key: dict[tuple[str, int], list[dict[str, object]]] = {}
    for component in components:
        key = (str(component["scheme"]), int(component["record_index"]))
        by_key.setdefault(key, []).append(component)

    rows: list[dict[str, object]] = []
    simulated_by_key: dict[tuple[str, int], np.ndarray] = {}
    for scheme_index, scheme in enumerate(schemes):
        for plateau in plateaus:
            if plateau["gap"] == 1 or plateau["N"] <= 1:
                continue
            key = (scheme.name, plateau["record_index"])
            parts = by_key.get(key, [])
            if not parts:
                raise StratifiedNullError("missing plateau components")
            expected = sum(float(part["expected_component"]) for part in parts)
            variance = sum(float(part["variance_component"]) for part in parts)
            observed = sum(int(part["observed_recurrences"]) for part in parts)
            rng = np.random.default_rng(
                seed + scheme_index * 100_000 + plateau["record_index"]
            )
            simulated = np.zeros(replications, dtype=np.int64)
            for part in parts:
                population = int(part["population_after_removal"])
                good = int(part["conditioned_gap_count_after_removal"])
                sample = int(part["plateau_exposure_after_removal"])
                if sample and population:
                    simulated += rng.hypergeometric(
                        good,
                        population - good,
                        sample,
                        size=replications,
                    )
            simulated_by_key[key] = simulated
            z_score = None if variance <= 0.0 else (observed - expected) / math.sqrt(variance)
            greater_p = (int(np.count_nonzero(simulated >= observed)) + 1) / (
                replications + 1
            )
            absolute_deviation = abs(observed - expected)
            two_sided_p = (
                int(np.count_nonzero(np.abs(simulated.astype(float) - expected) >= absolute_deviation))
                + 1
            ) / (replications + 1)
            stationary = p011_statistics.get(plateau["record_index"], {})
            low_components = sum(
                str(part["information_flag"]) == "LOW_INFORMATION" for part in parts
            )
            rows.append(
                {
                    "scheme": scheme.name,
                    "record_index": plateau["record_index"],
                    "start_prime": plateau["start_prime"],
                    "gap": plateau["gap"],
                    "post_record_trials": plateau["N"] - 1,
                    "observed_recurrences": observed,
                    "expected_recurrences": expected,
                    "variance": variance,
                    "standardized_residual_z": z_score,
                    "mc_greater_p": greater_p,
                    "mc_two_sided_p": two_sided_p,
                    "component_count": len(parts),
                    "low_information_component_count": low_components,
                    "information_flag": "LOW_INFORMATION" if low_components else "OK",
                    "cohorts": _cohorts_for_plateau(plateau),
                    "p011_expected_recurrences": stationary.get("p011_expected_recurrences"),
                    "p011_standardized_residual_z": stationary.get(
                        "p011_standardized_residual_z"
                    ),
                }
            )

    for scheme in schemes:
        scheme_rows = [row for row in rows if row["scheme"] == scheme.name]
        q_values = _bh_adjust([float(row["mc_greater_p"]) for row in scheme_rows])
        for row, q_value in zip(scheme_rows, q_values, strict=True):
            row["bh_q_greater_all_eligible"] = q_value

    cohort_summaries: list[dict[str, object]] = []
    for scheme in schemes:
        scheme_rows = [row for row in rows if row["scheme"] == scheme.name]
        for cohort in COHORTS:
            selected = [
                row
                for row in scheme_rows
                if cohort in row["cohorts"] and float(row["variance"]) > 0.0
            ]
            if not selected:
                cohort_summaries.append(
                    {"scheme": scheme.name, "cohort": cohort, "status": "EMPTY"}
                )
                continue
            observed_z = np.asarray(
                [float(row["standardized_residual_z"]) for row in selected]
            )
            max_simulated = np.zeros(replications, dtype=np.float64)
            for row in selected:
                expected = float(row["expected_recurrences"])
                variance = float(row["variance"])
                simulated = simulated_by_key[(scheme.name, int(row["record_index"]))]
                max_simulated = np.maximum(
                    max_simulated,
                    np.abs((simulated.astype(float) - expected) / math.sqrt(variance)),
                )
            observed_max = float(np.max(np.abs(observed_z)))
            family_p = (int(np.count_nonzero(max_simulated >= observed_max)) + 1) / (
                replications + 1
            )
            cohort_summaries.append(
                {
                    "status": "PASS",
                    "scheme": scheme.name,
                    "cohort": cohort,
                    "row_count": len(selected),
                    "observed_total_recurrences": sum(
                        int(row["observed_recurrences"]) for row in selected
                    ),
                    "expected_total_recurrences": sum(
                        float(row["expected_recurrences"]) for row in selected
                    ),
                    "observed_max_absolute_z": observed_max,
                    "monte_carlo_max_absolute_z_p": family_p,
                    "replications": replications,
                    "base_seed": seed,
                }
            )
    return {"rows": rows, "cohorts": cohort_summaries}


def compute_stratified_analysis(
    complete_plateaus_path: Path,
    p011_statistics_path: Path,
    *,
    analysis_limit: int = ANALYSIS_LIMIT,
    segment_span: int = DEFAULT_SEGMENT_SPAN,
    replications: int = DEFAULT_REPLICATIONS,
    seed: int = DEFAULT_SEED,
    require_pinned_hashes: bool = True,
    prime_chunks: Iterable[Sequence[int] | np.ndarray] | None = None,
) -> dict[str, object]:
    if analysis_limit not in KNOWN_PRIME_COUNTS:
        raise StratifiedNullError("analysis limit lacks a pinned independent pi(x)")
    plateaus = _load_plateaus(
        complete_plateaus_path, require_pinned_hash=require_pinned_hashes
    )
    p011 = _load_p011_statistics(
        p011_statistics_path, require_pinned_hash=require_pinned_hashes
    )
    chunks = (
        prime_chunks
        if prime_chunks is not None
        else iter_prime_chunks(analysis_limit, segment_span=segment_span)
    )
    accumulated = accumulate_bin_counts(chunks, plateaus)
    if int(accumulated["prime_count"]) != KNOWN_PRIME_COUNTS[analysis_limit]:
        raise StratifiedNullError("generated prime count disagrees with pinned pi(x)")
    if int(accumulated["gap_count"]) != KNOWN_PRIME_COUNTS[analysis_limit] - 1:
        raise StratifiedNullError("generated gap count disagrees with pinned pi(x)-1")
    components = build_components(plateaus, accumulated)
    inference = analyze_components(
        plateaus,
        components,
        p011,
        replications=replications,
        seed=seed,
    )
    return {
        "status": "PASS",
        "schema_version": SCHEMA_VERSION,
        "experiment": EXPERIMENT,
        "analysis_limit": analysis_limit,
        "segment_span": segment_span,
        "prime_count": accumulated["prime_count"],
        "gap_count": accumulated["gap_count"],
        "replications": replications,
        "base_seed": seed,
        "bin_schemes": [
            {"name": scheme.name, "width": scheme.width, "shift": scheme.shift}
            for scheme in BIN_SCHEMES
        ],
        "low_information_rule": {
            "conditioned_gap_count_less_than": LOW_INFORMATION_MIN_CONDITIONED_GAPS,
            "control_exposure_less_than": LOW_INFORMATION_MIN_CONTROL_EXPOSURE,
            "changes_test_membership": False,
        },
        "components": components,
        "rows": inference["rows"],
        "cohorts": inference["cohorts"],
        "primary_contract": {
            "scheme": BIN_SCHEMES[0].name,
            "cohort": "primary_start_ge_1000",
            "statistic": "two-sided family maximum absolute standardized residual",
        },
        "secondary_contract": "one-sided recurrence enrichment with BH q-values",
        "forced_first_record_removed": True,
        "post_selection_acknowledged": True,
        "theorem_claimed": False,
        "limitations": [
            "within-bin exchangeability is a diagnostic assumption, not a theorem",
            "record-gap selection remains post-selection",
            "separate gap categories are simulated independently despite shared prime-gap positions",
            "the development range reuses P006 and P011 data",
            "LOW_INFORMATION is descriptive and does not alter family membership",
        ],
    }


def validate_inputs(
    complete_plateaus_path: Path,
    p011_statistics_path: Path,
    *,
    analysis_limit: int = ANALYSIS_LIMIT,
    segment_span: int = DEFAULT_SEGMENT_SPAN,
) -> dict[str, object]:
    plateaus = _load_plateaus(complete_plateaus_path, require_pinned_hash=True)
    p011 = _load_p011_statistics(p011_statistics_path, require_pinned_hash=True)
    if analysis_limit != ANALYSIS_LIMIT or analysis_limit not in KNOWN_PRIME_COUNTS:
        raise StratifiedNullError("P012-A development range must be [2,10^9]")
    if not 1_000_000 <= segment_span <= 200_000_000:
        raise StratifiedNullError("segment span is outside the reviewed range")
    return {
        "status": "PASS",
        "experiment": EXPERIMENT,
        "analysis_limit": analysis_limit,
        "segment_span": segment_span,
        "complete_plateau_count": len(plateaus),
        "p011_comparison_row_count": len(p011),
        "replications": DEFAULT_REPLICATIONS,
        "seed": DEFAULT_SEED,
        "actual_experiment_executed": False,
    }


def _serializable_rows(rows: Sequence[dict[str, object]]) -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for row in rows:
        payload = dict(row)
        if isinstance(payload.get("cohorts"), list):
            payload["cohorts"] = ";".join(str(item) for item in payload["cohorts"])
        result.append(payload)
    return result


def _plot_comparison(rows: Sequence[dict[str, object]], directory: Path) -> list[Path]:
    import matplotlib.pyplot as plt

    directory.mkdir()
    primary = [
        row
        for row in rows
        if row["scheme"] == BIN_SCHEMES[0].name
        and "primary_start_ge_1000" in row["cohorts"]
    ]
    gaps = [int(row["gap"]) for row in primary]
    observed = [int(row["observed_recurrences"]) for row in primary]
    local_expected = [float(row["expected_recurrences"]) for row in primary]
    stationary_expected = [float(row["p011_expected_recurrences"]) for row in primary]
    stationary_z = [float(row["p011_standardized_residual_z"]) for row in primary]
    local_defined_indices: list[int] = []
    local_defined_z: list[float] = []
    local_undefined_indices: list[int] = []
    for index, row in enumerate(primary):
        value = row["standardized_residual_z"]
        if value is None:
            local_undefined_indices.append(index)
        else:
            local_defined_indices.append(index)
            local_defined_z.append(float(value))
    paths: list[Path] = []

    figure, axis = plt.subplots(figsize=(10, 5.5))
    axis.plot(gaps, observed, "o-", label="observed recurrence")
    axis.plot(gaps, stationary_expected, "s--", label="P011 stationary expected")
    axis.plot(gaps, local_expected, "^--", label="P012 stratified expected")
    axis.set_xlabel("record gap")
    axis.set_ylabel("recurrence count")
    axis.set_title("P012 local-stratified versus P011 stationary expectation")
    axis.grid(alpha=0.25)
    axis.legend()
    figure.tight_layout()
    for suffix in ("png", "pdf"):
        path = directory / f"p012_expected_comparison.{suffix}"
        figure.savefig(path, dpi=180 if suffix == "png" else None)
        paths.append(path)
    plt.close(figure)

    x = np.arange(len(gaps))
    figure, axis = plt.subplots(figsize=(11, 5.5))
    axis.axhline(0.0, color="black", linewidth=0.8)
    axis.bar(
        x - 0.2,
        stationary_z,
        width=0.4,
        color="tab:blue",
        label="P011 stationary z",
    )
    axis.bar(
        x[local_defined_indices] + 0.2,
        local_defined_z,
        width=0.4,
        color="tab:orange",
        label="P012 stratified z",
    )
    if local_undefined_indices:
        axis.scatter(
            x[local_undefined_indices] + 0.2,
            np.zeros(len(local_undefined_indices)),
            marker="x",
            s=52,
            linewidths=1.6,
            color="tab:orange",
            zorder=3,
            label="P012 z undefined (variance=0; not z=0)",
        )
    axis.set_xticks(x, [str(gap) for gap in gaps], rotation=90)
    axis.set_xlabel("record gap")
    axis.set_ylabel("standardized residual z")
    axis.set_title(
        "P012 residual comparison on the fixed primary cohort\n"
        "x marker denotes undefined P012 z when conditional variance is zero"
    )
    axis.grid(axis="y", alpha=0.25)
    axis.legend()
    figure.tight_layout()
    for suffix in ("png", "pdf"):
        path = directory / f"p012_residual_comparison.{suffix}"
        figure.savefig(path, dpi=180 if suffix == "png" else None)
        paths.append(path)
    plt.close(figure)
    return paths


def run_stratified_null(
    complete_plateaus_path: Path,
    p011_statistics_path: Path,
    output_directory: Path,
    *,
    approval_token: str | None,
    analysis_limit: int = ANALYSIS_LIMIT,
    segment_span: int = DEFAULT_SEGMENT_SPAN,
    replications: int = DEFAULT_REPLICATIONS,
    seed: int = DEFAULT_SEED,
    make_plots: bool = True,
) -> dict[str, object]:
    require_experiment_approval(approval_token)
    if output_directory.exists():
        raise FileExistsError(f"refusing to overwrite P012 result: {output_directory}")
    started = time.perf_counter()
    analysis = compute_stratified_analysis(
        complete_plateaus_path,
        p011_statistics_path,
        analysis_limit=analysis_limit,
        segment_span=segment_span,
        replications=replications,
        seed=seed,
    )
    output_directory.mkdir(parents=True)
    with (output_directory / "input_complete_plateaus.csv").open("xb") as handle:
        handle.write(complete_plateaus_path.read_bytes())
    with (output_directory / "input_p011_plateau_statistics.csv").open("xb") as handle:
        handle.write(p011_statistics_path.read_bytes())
    _write_json_exclusive(output_directory / "analysis.json", analysis)
    _write_csv_exclusive(
        output_directory / "bin_components.csv",
        _serializable_rows(analysis["components"]),
    )
    _write_csv_exclusive(
        output_directory / "plateau_statistics.csv",
        _serializable_rows(analysis["rows"]),
    )
    _write_json_exclusive(
        output_directory / "cohort_summary.json", {"cohorts": analysis["cohorts"]}
    )
    figure_paths = (
        _plot_comparison(analysis["rows"], output_directory / "figures")
        if make_plots
        else []
    )
    summary = {
        "status": "PASS",
        "experiment": EXPERIMENT,
        "analysis_limit": analysis_limit,
        "modeled_rows": len(analysis["rows"]),
        "component_rows": len(analysis["components"]),
        "replications": replications,
        "base_seed": seed,
        "elapsed_seconds": time.perf_counter() - started,
        "figure_count": len(figure_paths),
        "holdout_touched": False,
        "theorem_claimed": False,
        "gpu_used": False,
    }
    _write_json_exclusive(output_directory / "summary.json", summary)
    artifacts = sorted(path for path in output_directory.rglob("*") if path.is_file())
    manifest = {
        "status": "PASS",
        "experiment": EXPERIMENT,
        "schema_version": SCHEMA_VERSION,
        "input_sha256": {
            "complete_plateaus": COMPLETE_PLATEAUS_SHA256,
            "p011_plateau_statistics": P011_STATISTICS_SHA256,
        },
        "artifacts_sha256": {
            path.relative_to(output_directory).as_posix(): sha256_file(path)
            for path in artifacts
        },
        "replications": replications,
        "base_seed": seed,
        "analysis_limit": analysis_limit,
        "segment_span": segment_span,
        "holdout_touched": False,
        "theorem_claimed": False,
        "gpu_used": False,
    }
    _write_json_exclusive(output_directory / "manifest.json", manifest)
    return summary


def verify_saved_stratified_null(output_directory: Path) -> dict[str, object]:
    issues: list[str] = []
    try:
        manifest = json.loads((output_directory / "manifest.json").read_text("utf-8"))
        saved_analysis = json.loads((output_directory / "analysis.json").read_text("utf-8"))
        artifacts = manifest.get("artifacts_sha256", {})
        if not isinstance(artifacts, dict):
            raise StratifiedNullError("manifest artifact hashes are missing")
        for relative, expected in artifacts.items():
            path = output_directory / str(relative)
            if not path.is_file() or sha256_file(path) != str(expected):
                issues.append(f"artifact missing/hash mismatch: {relative}")
        recomputed = compute_stratified_analysis(
            output_directory / "input_complete_plateaus.csv",
            output_directory / "input_p011_plateau_statistics.csv",
            analysis_limit=int(manifest["analysis_limit"]),
            segment_span=int(manifest["segment_span"]),
            replications=int(manifest["replications"]),
            seed=int(manifest["base_seed"]),
        )
        if recomputed != saved_analysis:
            issues.append("saved analysis differs from deterministic full recomputation")
        if manifest.get("holdout_touched") is not False:
            issues.append("P012-A manifest incorrectly claims holdout access")
    except Exception as exc:
        issues.append(f"saved P012 verification failed: {type(exc).__name__}: {exc}")
    return {
        "status": "PASS" if not issues else "FAIL",
        "issues": issues,
        "deterministic_full_recomputation": "PASS" if not issues else "FAIL",
        "manifest_sha256": (
            hashlib.sha256((output_directory / "manifest.json").read_bytes()).hexdigest()
            if (output_directory / "manifest.json").is_file()
            else None
        ),
        "holdout_touched": False,
        "theorem_claimed": False,
    }


__all__ = [
    "ANALYSIS_LIMIT",
    "BIN_SCHEMES",
    "DEFAULT_REPLICATIONS",
    "DEFAULT_SEED",
    "EXPERIMENT",
    "StratifiedNullError",
    "accumulate_bin_counts",
    "analyze_components",
    "build_components",
    "compute_stratified_analysis",
    "run_stratified_null",
    "validate_inputs",
    "verify_saved_stratified_null",
]
